project:
  type: website

website:
  title: "Proyecto-Seguridad"
  navbar:
    left:
      - href: index.qmd
        text: "Inicio"

format:
  html:
    toc: true
    toc_float: true
    code-fold: show
    output_file: index.html

editor: visual

