<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="es" xml:lang="es"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="David Rodríguez Valenzuela">
<meta name="author" content="Fernando Sepúlveda Retamal">

<title>Proyecto-Seguridad: Análisis de Clusters en torno a la Percepción de Inseguridad en Chile – Proyecto-Seguridad</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "Sin resultados",
    "search-matching-documents-text": "documentos encontrados",
    "search-copy-link-title": "Copiar el enlace en la búsqueda",
    "search-hide-matches-text": "Ocultar resultados adicionales",
    "search-more-match-text": "resultado adicional en este documento",
    "search-more-matches-text": "resultados adicionales en este documento",
    "search-clear-button-title": "Borrar",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancelar",
    "search-submit-button-title": "Enviar",
    "search-label": "Buscar"
  }
}</script>


<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Proyecto-Seguridad</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Buscar"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Navegación de palanca" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link active" href="./index.html" aria-current="page"> 
<span class="menu-text">Inicio</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">En esta página</h2>
   
  <ul>
  <li><a href="#introducción" id="toc-introducción" class="nav-link active" data-scroll-target="#introducción">Introducción</a></li>
  <li><a href="#análisis-descriptivo" id="toc-análisis-descriptivo" class="nav-link" data-scroll-target="#análisis-descriptivo">Análisis Descriptivo</a>
  <ul class="collapse">
  <li><a href="#matriz-de-correlación-variables-inseguridad" id="toc-matriz-de-correlación-variables-inseguridad" class="nav-link" data-scroll-target="#matriz-de-correlación-variables-inseguridad">Matriz de correlación variables inseguridad</a></li>
  <li><a href="#análisis-de-las-variables-sociodemográficas" id="toc-análisis-de-las-variables-sociodemográficas" class="nav-link" data-scroll-target="#análisis-de-las-variables-sociodemográficas">Análisis de las variables sociodemográficas:</a></li>
  <li><a href="#matriz-de-correlación-variables-sociodemográficas-e-inseguridad" id="toc-matriz-de-correlación-variables-sociodemográficas-e-inseguridad" class="nav-link" data-scroll-target="#matriz-de-correlación-variables-sociodemográficas-e-inseguridad">Matriz de correlación variables sociodemográficas e inseguridad</a></li>
  <li><a href="#anova" id="toc-anova" class="nav-link" data-scroll-target="#anova">Anova</a></li>
  </ul></li>
  <li><a href="#análisis-de-componentes-principales-pca" id="toc-análisis-de-componentes-principales-pca" class="nav-link" data-scroll-target="#análisis-de-componentes-principales-pca">Análisis de Componentes Principales (PCA)</a>
  <ul class="collapse">
  <li><a href="#mostramos-gráficamente-cómo-las-variables-contribuyen-a-pc1-y-pc2." id="toc-mostramos-gráficamente-cómo-las-variables-contribuyen-a-pc1-y-pc2." class="nav-link" data-scroll-target="#mostramos-gráficamente-cómo-las-variables-contribuyen-a-pc1-y-pc2.">Mostramos gráficamente cómo las variables contribuyen a PC1 y PC2.</a></li>
  <li><a href="#interpretación-del-gráfico-de-cargas-en-los-primeros-dos-componentes-principales" id="toc-interpretación-del-gráfico-de-cargas-en-los-primeros-dos-componentes-principales" class="nav-link" data-scroll-target="#interpretación-del-gráfico-de-cargas-en-los-primeros-dos-componentes-principales">Interpretación del gráfico de cargas en los primeros dos componentes principales</a></li>
  </ul></li>
  <li><a href="#análisis-de-clusters" id="toc-análisis-de-clusters" class="nav-link" data-scroll-target="#análisis-de-clusters">Análisis de clusters</a>
  <ul class="collapse">
  <li><a href="#regresión-lineal" id="toc-regresión-lineal" class="nav-link" data-scroll-target="#regresión-lineal">Regresión Lineal</a>
  <ul class="collapse">
  <li><a href="#cruce-de-clusters-con-variables-sociodemográficas-seleccionadas" id="toc-cruce-de-clusters-con-variables-sociodemográficas-seleccionadas" class="nav-link" data-scroll-target="#cruce-de-clusters-con-variables-sociodemográficas-seleccionadas">Cruce de clusters con variables sociodemográficas seleccionadas</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#conclusiones" id="toc-conclusiones" class="nav-link" data-scroll-target="#conclusiones">Conclusiones</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Proyecto-Seguridad: Análisis de Clusters en torno a la Percepción de Inseguridad en Chile</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Autores/as</div>
    <div class="quarto-title-meta-contents">
             <p>David Rodríguez Valenzuela </p>
             <p>Fernando Sepúlveda Retamal </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Fecha de publicación</div>
    <div class="quarto-title-meta-contents">
      <p class="date">26 de enero de 2025</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="introducción" class="level1">
<h1>Introducción</h1>
<p>En el presente trabajo, se analizarán diversas variables incluidas en la encuesta ENUSC 2023, con la finalidad de observar la manera en que los tipos de percepción de inseguridad capturados en base al análisis, se relacionan con ciertas características de la población, como la edad, nivel educacional, sexo, nivel socioeconómico, entre otros factores. De tal manera, a través de este trabajo se buscarán agrupar los diversos tipos de inseguridad declarados por las personas entrevistadas, con el objetivo de caracterizar sociodemográficamente las diversas variables de este tipo, que determinan los perfiles de inseguridad existentes en la sociedad chilena.</p>
</section>
<section id="análisis-descriptivo" class="level1">
<h1>Análisis Descriptivo</h1>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Análisis de variables de inseguridad</caption>
<colgroup>
<col style="width: 16%">
<col style="width: 4%">
<col style="width: 5%">
<col style="width: 7%">
<col style="width: 8%">
<col style="width: 5%">
<col style="width: 7%">
<col style="width: 5%">
<col style="width: 3%">
<col style="width: 3%">
<col style="width: 5%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 8%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">vars</th>
<th style="text-align: right;">n</th>
<th style="text-align: right;">mean</th>
<th style="text-align: right;">sd</th>
<th style="text-align: right;">median</th>
<th style="text-align: right;">trimmed</th>
<th style="text-align: right;">mad</th>
<th style="text-align: right;">min</th>
<th style="text-align: right;">max</th>
<th style="text-align: right;">range</th>
<th style="text-align: right;">skew</th>
<th style="text-align: right;">kurtosis</th>
<th style="text-align: right;">se</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">P_AUMENTO_PAIS</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">48262</td>
<td style="text-align: right;">2.879346</td>
<td style="text-align: right;">0.3641719</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">2.990754</td>
<td style="text-align: right;">0.0000</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">-3.1153208</td>
<td style="text-align: right;">9.6161273</td>
<td style="text-align: right;">0.0016577</td>
</tr>
<tr class="even">
<td style="text-align: left;">P_AUMENTO_COM</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">47776</td>
<td style="text-align: right;">2.757410</td>
<td style="text-align: right;">0.4774425</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">2.849380</td>
<td style="text-align: right;">0.0000</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">-1.7920908</td>
<td style="text-align: right;">2.3659362</td>
<td style="text-align: right;">0.0021843</td>
</tr>
<tr class="odd">
<td style="text-align: left;">P_AUMENTO_BARRIO</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">47678</td>
<td style="text-align: right;">2.462939</td>
<td style="text-align: right;">0.5994455</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">2.522861</td>
<td style="text-align: right;">0.0000</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">-0.6281963</td>
<td style="text-align: right;">-0.5509168</td>
<td style="text-align: right;">0.0027453</td>
</tr>
<tr class="even">
<td style="text-align: left;">P_INSEG_LUGARES_1</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">29604</td>
<td style="text-align: right;">2.558404</td>
<td style="text-align: right;">0.7280209</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">2.516382</td>
<td style="text-align: right;">1.4826</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">0.1488447</td>
<td style="text-align: right;">-0.3417511</td>
<td style="text-align: right;">0.0042312</td>
</tr>
<tr class="odd">
<td style="text-align: left;">P_INSEG_LUGARES_2</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">39162</td>
<td style="text-align: right;">2.705812</td>
<td style="text-align: right;">0.6846334</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">2.652091</td>
<td style="text-align: right;">1.4826</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">0.1551784</td>
<td style="text-align: right;">-0.4817586</td>
<td style="text-align: right;">0.0034596</td>
</tr>
<tr class="even">
<td style="text-align: left;">P_INSEG_LUGARES_3</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">37189</td>
<td style="text-align: right;">2.662642</td>
<td style="text-align: right;">0.6631788</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">2.608140</td>
<td style="text-align: right;">1.4826</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">0.1719235</td>
<td style="text-align: right;">-0.4151163</td>
<td style="text-align: right;">0.0034389</td>
</tr>
<tr class="odd">
<td style="text-align: left;">P_INSEG_LUGARES_4</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">36146</td>
<td style="text-align: right;">2.403890</td>
<td style="text-align: right;">0.6221488</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">2.361885</td>
<td style="text-align: right;">0.0000</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">0.5465588</td>
<td style="text-align: right;">0.0522887</td>
<td style="text-align: right;">0.0032724</td>
</tr>
<tr class="even">
<td style="text-align: left;">P_INSEG_LUGARES_5</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">26765</td>
<td style="text-align: right;">2.403774</td>
<td style="text-align: right;">0.6706427</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">2.361836</td>
<td style="text-align: right;">0.0000</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">0.4959584</td>
<td style="text-align: right;">0.0527088</td>
<td style="text-align: right;">0.0040993</td>
</tr>
<tr class="odd">
<td style="text-align: left;">P_INSEG_LUGARES_6</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">20211</td>
<td style="text-align: right;">2.480283</td>
<td style="text-align: right;">0.6970246</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">2.448822</td>
<td style="text-align: right;">1.4826</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">0.2583631</td>
<td style="text-align: right;">-0.2090461</td>
<td style="text-align: right;">0.0049029</td>
</tr>
<tr class="even">
<td style="text-align: left;">P_INSEG_LUGARES_7</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">37192</td>
<td style="text-align: right;">2.376855</td>
<td style="text-align: right;">0.5938568</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">2.345029</td>
<td style="text-align: right;">0.0000</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">0.4959349</td>
<td style="text-align: right;">0.0223305</td>
<td style="text-align: right;">0.0030793</td>
</tr>
<tr class="odd">
<td style="text-align: left;">P_INSEG_LUGARES_8</td>
<td style="text-align: right;">11</td>
<td style="text-align: right;">35203</td>
<td style="text-align: right;">2.764480</td>
<td style="text-align: right;">0.6648099</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">2.721585</td>
<td style="text-align: right;">0.0000</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">0.0446421</td>
<td style="text-align: right;">-0.3737311</td>
<td style="text-align: right;">0.0035433</td>
</tr>
<tr class="even">
<td style="text-align: left;">P_INSEG_LUGARES_9</td>
<td style="text-align: right;">12</td>
<td style="text-align: right;">23022</td>
<td style="text-align: right;">2.131874</td>
<td style="text-align: right;">0.5927919</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">2.133294</td>
<td style="text-align: right;">0.0000</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">0.5840197</td>
<td style="text-align: right;">1.2906201</td>
<td style="text-align: right;">0.0039069</td>
</tr>
<tr class="odd">
<td style="text-align: left;">P_INSEG_LUGARES_10</td>
<td style="text-align: right;">13</td>
<td style="text-align: right;">44257</td>
<td style="text-align: right;">2.435795</td>
<td style="text-align: right;">0.6001441</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">2.407066</td>
<td style="text-align: right;">0.0000</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">0.3887108</td>
<td style="text-align: right;">-0.2181760</td>
<td style="text-align: right;">0.0028528</td>
</tr>
<tr class="even">
<td style="text-align: left;">P_INSEG_LUGARES_11</td>
<td style="text-align: right;">14</td>
<td style="text-align: right;">34656</td>
<td style="text-align: right;">2.615334</td>
<td style="text-align: right;">0.6527748</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">2.567265</td>
<td style="text-align: right;">1.4826</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">0.2316110</td>
<td style="text-align: right;">-0.3999272</td>
<td style="text-align: right;">0.0035065</td>
</tr>
<tr class="odd">
<td style="text-align: left;">P_INSEG_LUGARES_12</td>
<td style="text-align: right;">15</td>
<td style="text-align: right;">41955</td>
<td style="text-align: right;">2.534454</td>
<td style="text-align: right;">0.6568466</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">2.486549</td>
<td style="text-align: right;">1.4826</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">0.3515384</td>
<td style="text-align: right;">-0.3018263</td>
<td style="text-align: right;">0.0032068</td>
</tr>
<tr class="even">
<td style="text-align: left;">P_INSEG_LUGARES_13</td>
<td style="text-align: right;">16</td>
<td style="text-align: right;">46981</td>
<td style="text-align: right;">2.276793</td>
<td style="text-align: right;">0.5504089</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">2.229400</td>
<td style="text-align: right;">0.0000</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">0.8275917</td>
<td style="text-align: right;">0.8089483</td>
<td style="text-align: right;">0.0025394</td>
</tr>
<tr class="odd">
<td style="text-align: left;">P_INSEG_LUGARES_14</td>
<td style="text-align: right;">17</td>
<td style="text-align: right;">28632</td>
<td style="text-align: right;">2.096046</td>
<td style="text-align: right;">0.6298400</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">2.086091</td>
<td style="text-align: right;">0.0000</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">0.5759080</td>
<td style="text-align: right;">1.1599810</td>
<td style="text-align: right;">0.0037222</td>
</tr>
<tr class="even">
<td style="text-align: left;">P_INSEG_LUGARES_15</td>
<td style="text-align: right;">18</td>
<td style="text-align: right;">6280</td>
<td style="text-align: right;">1.954299</td>
<td style="text-align: right;">0.6184873</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">1.921776</td>
<td style="text-align: right;">0.0000</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">0.4569360</td>
<td style="text-align: right;">1.1145425</td>
<td style="text-align: right;">0.0078046</td>
</tr>
<tr class="odd">
<td style="text-align: left;">P_INSEG_LUGARES_16</td>
<td style="text-align: right;">19</td>
<td style="text-align: right;">39218</td>
<td style="text-align: right;">2.505278</td>
<td style="text-align: right;">0.6708918</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">2.466312</td>
<td style="text-align: right;">1.4826</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">0.3009707</td>
<td style="text-align: right;">-0.2318630</td>
<td style="text-align: right;">0.0033877</td>
</tr>
<tr class="even">
<td style="text-align: left;">P_INSEG_OSCURO_1</td>
<td style="text-align: right;">20</td>
<td style="text-align: right;">43800</td>
<td style="text-align: right;">2.934452</td>
<td style="text-align: right;">0.7262737</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">2.936073</td>
<td style="text-align: right;">0.0000</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">-0.1252515</td>
<td style="text-align: right;">-0.5615778</td>
<td style="text-align: right;">0.0034703</td>
</tr>
<tr class="odd">
<td style="text-align: left;">P_INSEG_DIA_1</td>
<td style="text-align: right;">21</td>
<td style="text-align: right;">47593</td>
<td style="text-align: right;">2.232660</td>
<td style="text-align: right;">0.5751397</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">2.203362</td>
<td style="text-align: right;">0.0000</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">0.6701075</td>
<td style="text-align: right;">0.9526756</td>
<td style="text-align: right;">0.0026363</td>
</tr>
<tr class="even">
<td style="text-align: left;">P_INSEG_OSCURO_2</td>
<td style="text-align: right;">22</td>
<td style="text-align: right;">48350</td>
<td style="text-align: right;">2.196174</td>
<td style="text-align: right;">0.6262557</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">2.195424</td>
<td style="text-align: right;">0.0000</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">0.5254746</td>
<td style="text-align: right;">0.7697802</td>
<td style="text-align: right;">0.0028481</td>
</tr>
<tr class="odd">
<td style="text-align: left;">P_INSEG_DIA_2</td>
<td style="text-align: right;">23</td>
<td style="text-align: right;">48417</td>
<td style="text-align: right;">1.974121</td>
<td style="text-align: right;">0.5355538</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">1.954202</td>
<td style="text-align: right;">0.0000</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">0.3969210</td>
<td style="text-align: right;">2.1269793</td>
<td style="text-align: right;">0.0024339</td>
</tr>
</tbody>
</table>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/pre-procesamiento-2-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>En base a los resultados arrojados por el gráfico, y en relación a las variables de percepción de aumento de delincuencia (“P_AUMENTO_PAIS”, “P_AUMENTO_COM”, “P_AUMENTO_BARRIO”), podemos indicar:</p>
<p>“P_AUMENTO_PAIS” tiene una media de 2,879, lo que indica una percepción general de aumento en el nivel de delincuencia durante los últimos 12 meses. “P_AUMENTO_COM” y “P_AUMENTO_BARRIO” tienen medias menores (2,756 y 2,461), indicando que la percepción de aumento de la delincuencia es menor a nivel local.En base a la información arrojada, podemos establecer que las personas tienden a considerar a su unidad territorial próxima mayormente segura, mientras que a aquella que se encuentra más lejana (comuna y país), se observa mayormente afectada por el fenómeno delictivo.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/graficos-inseguridad-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/graficos-inseguridad-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/graficos-inseguridad-3.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/graficos-inseguridad-4.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/graficos-inseguridad-5.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/graficos-inseguridad-6.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/graficos-inseguridad-7.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/graficos-inseguridad-8.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>En base a los histogramas y estadísticos descriptivos, las variables que reflejan mayor inseguridad son:</p>
<ol type="1">
<li><p>“P_INSEG_OSCURO_1” (Media: 2,932): Representa la percepción de inseguridad al caminar solo/a por el barrio durante la noche. Su media más alta indica que las personas se sienten significativamente menos seguras en esta situación. Este resultado podría estar relacionado con factores como la falta de iluminación, la presencia limitada de vigilancia y el miedo al crimen en horarios nocturnos.</p></li>
<li><p>“P_INSEG_LUGARES_8” (Media: 2,762): Representa la percepción de inseguridad en terminales de buses o ferrocarriles. La alta percepción de inseguridad puede estar asociada a la concurrencia de personas desconocidas, áreas mal vigiladas o actividades delictivas comunes en estos lugares.</p></li>
<li><p>“P_INSEG_LUGARES_2” (Media: 2,703): Evalúa la percepción de seguridad al esperar transporte público. La inseguridad en esta situación podría estar influenciada por tiempos de espera prolongados, áreas poco iluminadas y la exposición al robo o acoso mientras se espera.</p></li>
</ol>
<p>Variables que reflejan menor inseguridad:</p>
<ol type="1">
<li><p>“P_INSEG_DIA_2” (Media: 1,975): Representa la percepción de inseguridad al estar solo/a en casa durante el día. La media más baja indica que las personas se sienten mayoritariamente seguras en esta situación. Esto puede atribuirse a que estar en casa durante el día se percibe como una situación de menor riesgo, con menos probabilidades de encuentros con desconocidos o eventos delictivos.</p></li>
<li><p>“P_INSEG_LUGARES_15” (Media: 1,96): Evalúa la percepción de seguridad en el lugar de estudio. Este bajo nivel de inseguridad sugiere que los lugares de estudio están asociados a entornos relativamente controlados y protegidos, con supervisión activa y menor riesgo de incidentes.</p></li>
<li><p>“P_INSEG_LUGARES_14” (Media: 2,097): Representa la percepción de seguridad en el lugar de trabajo. Aunque ligeramente más alta que las anteriores, sigue indicando un nivel bajo de inseguridad percibida. Los lugares de trabajo suelen estar bien iluminados, vigilados y organizados, lo que contribuye a una mayor sensación de seguridad.</p></li>
</ol>
<section id="matriz-de-correlación-variables-inseguridad" class="level2">
<h2 class="anchored" data-anchor-id="matriz-de-correlación-variables-inseguridad">Matriz de correlación variables inseguridad</h2>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.1037133 1.0000000</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/matriz-correlacion-inseguridad-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Podemos observar, en base a la matriz de correlaciones, que todas las variables relativas a la percepción de inseguridad, tienen una relación positiva, con un valor R mínimo de 0,1. En general, se observan valores medios y medios altos de correlación, lo que tiene sentido, si se considera que todo el set de preguntas incluidas en esta matriz de correlación, se deriva de la percepción de inseguridad. Más allá de lo anterior, hay zonas del gráfico claramente más coloridas y otras que indican menores niveles de correlación, punto a considerar para un posterior análisis de reducción de dimensionalidad.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Análisis de variables sociodemográficas</caption>
<colgroup>
<col style="width: 19%">
<col style="width: 3%">
<col style="width: 4%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 5%">
<col style="width: 7%">
<col style="width: 5%">
<col style="width: 3%">
<col style="width: 3%">
<col style="width: 4%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 7%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">vars</th>
<th style="text-align: right;">n</th>
<th style="text-align: right;">mean</th>
<th style="text-align: right;">sd</th>
<th style="text-align: right;">median</th>
<th style="text-align: right;">trimmed</th>
<th style="text-align: right;">mad</th>
<th style="text-align: right;">min</th>
<th style="text-align: right;">max</th>
<th style="text-align: right;">range</th>
<th style="text-align: right;">skew</th>
<th style="text-align: right;">kurtosis</th>
<th style="text-align: right;">se</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">rph_sexo</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">48552</td>
<td style="text-align: right;">1.5597298</td>
<td style="text-align: right;">0.4964246</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">1.5746614</td>
<td style="text-align: right;">0.0000</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">-0.2406349</td>
<td style="text-align: right;">-1.9421349</td>
<td style="text-align: right;">0.0022529</td>
</tr>
<tr class="even">
<td style="text-align: left;">rph_idgen</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">48372</td>
<td style="text-align: right;">1.5608617</td>
<td style="text-align: right;">0.4968700</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">1.5757145</td>
<td style="text-align: right;">0.0000</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">-0.2381841</td>
<td style="text-align: right;">-1.9243659</td>
<td style="text-align: right;">0.0022592</td>
</tr>
<tr class="odd">
<td style="text-align: left;">rph_pertenencia_indigena</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">48552</td>
<td style="text-align: right;">0.0906039</td>
<td style="text-align: right;">0.2870479</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0.0000000</td>
<td style="text-align: right;">0.0000</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2.8523993</td>
<td style="text-align: right;">6.1363083</td>
<td style="text-align: right;">0.0013027</td>
</tr>
<tr class="even">
<td style="text-align: left;">rph_nacionalidad</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">48552</td>
<td style="text-align: right;">1.0613157</td>
<td style="text-align: right;">0.2399110</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1.0000000</td>
<td style="text-align: right;">0.0000</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">3.6569838</td>
<td style="text-align: right;">11.3737647</td>
<td style="text-align: right;">0.0010888</td>
</tr>
<tr class="odd">
<td style="text-align: left;">rph_nivel</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">48552</td>
<td style="text-align: right;">2.1750700</td>
<td style="text-align: right;">0.7294789</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">2.2281551</td>
<td style="text-align: right;">1.4826</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">-0.3980339</td>
<td style="text-align: right;">-0.6634254</td>
<td style="text-align: right;">0.0033106</td>
</tr>
<tr class="even">
<td style="text-align: left;">rph_situacion_laboral_a</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">48552</td>
<td style="text-align: right;">0.5565167</td>
<td style="text-align: right;">0.4968007</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.5706452</td>
<td style="text-align: right;">0.0000</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">-0.2275180</td>
<td style="text-align: right;">-1.9482757</td>
<td style="text-align: right;">0.0022546</td>
</tr>
<tr class="odd">
<td style="text-align: left;">rph_edad</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">48552</td>
<td style="text-align: right;">4.2613487</td>
<td style="text-align: right;">1.8156855</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">4.2747026</td>
<td style="text-align: right;">2.9652</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">-0.0353487</td>
<td style="text-align: right;">-1.1228258</td>
<td style="text-align: right;">0.0082402</td>
</tr>
<tr class="even">
<td style="text-align: left;">rph_nse</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">48552</td>
<td style="text-align: right;">1.6642775</td>
<td style="text-align: right;">0.7048051</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">1.5803512</td>
<td style="text-align: right;">1.4826</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0.5781493</td>
<td style="text-align: right;">-0.8414490</td>
<td style="text-align: right;">0.0031986</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="análisis-de-las-variables-sociodemográficas" class="level2">
<h2 class="anchored" data-anchor-id="análisis-de-las-variables-sociodemográficas">Análisis de las variables sociodemográficas:</h2>
<ol type="1">
<li><p>“rph_sexo”:</p>
<p>Rango: 1 (Hombre) a 2 (Mujer). Distribución: La mediana (2,000) y la media (1,55) indican una ligera mayoría de mujeres en la muestra.</p></li>
<li><p>“rph_idgen”:</p>
<p>Rango: 1 (Masculino) a 3 (Trans u otro). Distribución: La mediana (2,0) y la media (1,55) reflejan que la mayoría de los encuestados se identifica como masculino o femenino, mientras que una pequeña proporción se identifica como “Trans u otro”.</p></li>
<li><p>“rph_pertenencia_indigena”: Rango: 0 (No pertenece) a 1 (Pertenece). Distribución: La media (0,09) indica que menos del 10% de los encuestados pertenece a un pueblo indígena, que se condice con resultados arrojados por instrumentos como CENSO 0217 y encuestas de opinión pública, las que arrojan que alrededor del 10% de nuestra población se identifica como perteneciente a un pueblo indígena..</p></li>
<li><p>“rph_nacionalidad”: Rango: 1 (Chilena) a 2 (Chilena y/u otra). Distribución: La mediana (1,0) y la media (1,06) reflejan que la mayoría de los encuestados se identifica exclusivamente como chilenos.</p></li>
<li><p>“rph_nivel” (Nivel educacional):</p>
<p>Rango: 0 (Nunca asistió) a 3 (Educación superior). Distribución: La mediana (2,0) y la media (2,1) indican que la mayoría de los encuestados tiene educación secundaria o superior, con un número considerable alcanzando estudios superiores.</p></li>
<li><p>“rph_situacion_laboral_a” (Situación laboral actual):</p>
<p>Rango: 0 (No) a 1 (Sí). Distribución: La media (0,56) indica que aproximadamente el 56% de los encuestados estaba trabajando al momento de contestar la encuesta.</p></li>
<li><p>“rph_edad”:</p>
<p>Rango: 1 (0 a 14 años) a 7 (70 años o más). Distribución: La media (4,26) y la mediana (4,0) sugieren que la población está principalmente concentrada en rangos de edad entre 30 y 49 años. Debemos considerar que no hay personas incluidas en la categoría 1 de “rph_edad”, esto dado que al filtrar la base de datos a través de la variable “Kish”, sólo estamos considerando la información de personas informantes, quienes no deben tener menos de 15 años para poder contestar la encuesta ENUSC, según lo indica el documento “Manual de Usuario de la Base de Datos ENUSC 2023”, en su página 14.</p></li>
<li><p>“rph_nse” (Nivel socioeconómico):</p>
<p>Rango: 1 (NSE bajo) a 3 (NSE alto). Distribución: La mediana (2,0) y la media (1,66) reflejan que la mayoría de los encuestados pertenece a niveles socioeconómicos bajos o medios.</p></li>
</ol>
<p>De tal manera, las variables sociodemográficas muestran una población diversa, con una mayoría femenina, concentrada entre los 30 y 49 años. La mayoría de los encuestados tiene educación secundaria o superior, pertenece a niveles socioeconómicos bajos o medios, y está laboralmente activo.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/indice-inseguridad-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>En base a los estadísticos descriptivos y la visualización gráfica, podemos establecer que tanto la percepción de inseguridad, como la percepción de aumento de la delincuencia se encuentran, en términos generales, en un rango medio-alto de la distribución. De tal manera, la mayor parte de los entrevistados tiene una evaluación negativa respecto a la condición de seguridad del país en la actualidad.</p>
</section>
<section id="matriz-de-correlación-variables-sociodemográficas-e-inseguridad" class="level2">
<h2 class="anchored" data-anchor-id="matriz-de-correlación-variables-sociodemográficas-e-inseguridad">Matriz de correlación variables sociodemográficas e inseguridad</h2>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/matriz-correlacion-sociodemo-inseguridad-2-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Como podemos observar, los coeficientes de correlación entre las variables sociodemográficas y los índices de inseguridad son débiles. Esto podría deberse a que la sensación de inseguridad podría entenderse como un fenómeno transversal en la población, lo que sugiere que es necesario identificar perfiles sociodemográficos específicos y analizar cómo se relacionan con la percepción de inseguridad a nivel general. Más allá de lo anterior, los resultados permiten identificar que variables como el sexo, la edad y el nivel socioeconómico podrían ser factores relevantes en este fenómeno. De manera más limitada, la nacionalidad y la situación laboral también parecen tener cierta influencia en las percepciones de inseguridad y delincuencia en el territorio.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/matriz-correlacion-sociodemo-delincuencia-2-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Esta matriz de correlación refuerza en cierta medida nuestras observaciones. Parece que las variables sociodemográficas tienen comportamientos distintos en relación con la percepción de inseguridad, lo que sugiere que la especificidad de estas variables no se refleja completamente en su generalidad.</p>
<p>Asimismo, las correlaciones positivas observadas en las variables de sexo y edad, en contraste con las negativas asociadas al nivel socioeconómico y educativo, indican patrones de comportamiento diversos. Esto resalta la necesidad de diferenciar estos comportamientos a través de perfiles sociodemográficos más específicos que los capturen de manera adecuada. Asimismo, una mayor especificidad en dichos perfiles debería hacer las correlaciones en torno a la inseguridad más claras.</p>
<p>##T-test</p>
<p>Observando diferencias intra-grupales en variables sociodemográficas, según percepción de inseguridad utilizando índices construidos.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Prueba T para Indice de Inseguridad por Sexo</caption>
<colgroup>
<col style="width: 2%">
<col style="width: 10%">
<col style="width: 5%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 21%">
<col style="width: 21%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">Estadístico.t</th>
<th style="text-align: right;">Valor.p</th>
<th style="text-align: right;">Grados.de.libertad</th>
<th style="text-align: right;">Media.del.grupo.1</th>
<th style="text-align: right;">Media.del.grupo.2</th>
<th style="text-align: right;">Intervalo.de.confianza..Inf.</th>
<th style="text-align: right;">Intervalo.de.confianza..Sup.</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">t</td>
<td style="text-align: right;">-39.36351</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">45910</td>
<td style="text-align: right;">2.337748</td>
<td style="text-align: right;">2.481456</td>
<td style="text-align: right;">-0.1508634</td>
<td style="text-align: right;">-0.1365522</td>
</tr>
</tbody>
</table>
</div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Prueba T para Indice de Delincuencia por Sexo</caption>
<colgroup>
<col style="width: 2%">
<col style="width: 10%">
<col style="width: 5%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 21%">
<col style="width: 21%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">Estadístico.t</th>
<th style="text-align: right;">Valor.p</th>
<th style="text-align: right;">Grados.de.libertad</th>
<th style="text-align: right;">Media.del.grupo.1</th>
<th style="text-align: right;">Media.del.grupo.2</th>
<th style="text-align: right;">Intervalo.de.confianza..Inf.</th>
<th style="text-align: right;">Intervalo.de.confianza..Sup.</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">t</td>
<td style="text-align: right;">-19.21143</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">45910</td>
<td style="text-align: right;">2.337748</td>
<td style="text-align: right;">2.481456</td>
<td style="text-align: right;">-0.1508634</td>
<td style="text-align: right;">-0.1365522</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>En base a las pruebas T para verificar diferencias entre grupos, podemos observar que las mujeres reportan un nivel promedio de inseguridad significativamente mayor que los hombres. Aunque la diferencia es pequeña, es estadísticamente significativa debido al gran tamaño muestral.</p>
<p>Análogamente, las mujeres tienen un promedio significativamente más alto en el índice de percepción de delincuencia que los hombres. De igual forma, aunque esa diferencia es pequeña, sigue siendo estadísticamente significativa.</p>
</section>
<section id="anova" class="level2">
<h2 class="anchored" data-anchor-id="anova">Anova</h2>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Anova para indice de inseguridad y nivel socioeconomico</caption>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">Df</th>
<th style="text-align: right;">Sum Sq</th>
<th style="text-align: right;">Mean Sq</th>
<th style="text-align: right;">F value</th>
<th style="text-align: right;">Pr(&gt;F)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">factor(rph_nse)</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">77.64888</td>
<td style="text-align: right;">38.8244385</td>
<td style="text-align: right;">238.3817</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Residuals</td>
<td style="text-align: right;">48461</td>
<td style="text-align: right;">7892.68313</td>
<td style="text-align: right;">0.1628667</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
</tbody>
</table>
</div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Anoca para indice de delincuencia y nivel socioeconomico</caption>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">Df</th>
<th style="text-align: right;">Sum Sq</th>
<th style="text-align: right;">Mean Sq</th>
<th style="text-align: right;">F value</th>
<th style="text-align: right;">Pr(&gt;F)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">factor(rph_nse)</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">28.00639</td>
<td style="text-align: right;">14.0031971</td>
<td style="text-align: right;">95.57534</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Residuals</td>
<td style="text-align: right;">48461</td>
<td style="text-align: right;">7100.25119</td>
<td style="text-align: right;">0.1465147</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
</tbody>
</table>
</div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Prueba de Tukey para índice de inseguridad y nivel socioeconómico</caption>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">diff</th>
<th style="text-align: right;">lwr</th>
<th style="text-align: right;">upr</th>
<th style="text-align: right;">p adj</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">2-1</td>
<td style="text-align: right;">-0.0164342</td>
<td style="text-align: right;">-0.0257249</td>
<td style="text-align: right;">-0.0071435</td>
<td style="text-align: right;">0.0001004</td>
</tr>
<tr class="even">
<td style="text-align: left;">3-1</td>
<td style="text-align: right;">-0.1217930</td>
<td style="text-align: right;">-0.1349832</td>
<td style="text-align: right;">-0.1086028</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3-2</td>
<td style="text-align: right;">-0.1053588</td>
<td style="text-align: right;">-0.1188557</td>
<td style="text-align: right;">-0.0918619</td>
<td style="text-align: right;">0.0000000</td>
</tr>
</tbody>
</table>
</div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Prueba de Tukey para índice de delincuencia y nivel socioeconómico</caption>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">diff</th>
<th style="text-align: right;">lwr</th>
<th style="text-align: right;">upr</th>
<th style="text-align: right;">p adj</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">2-1</td>
<td style="text-align: right;">-0.0019419</td>
<td style="text-align: right;">-0.0107539</td>
<td style="text-align: right;">0.0068701</td>
<td style="text-align: right;">0.8633011</td>
</tr>
<tr class="even">
<td style="text-align: left;">3-1</td>
<td style="text-align: right;">-0.0707803</td>
<td style="text-align: right;">-0.0832908</td>
<td style="text-align: right;">-0.0582698</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3-2</td>
<td style="text-align: right;">-0.0688384</td>
<td style="text-align: right;">-0.0816398</td>
<td style="text-align: right;">-0.0560370</td>
<td style="text-align: right;">0.0000000</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Respecto a las diferencias en Índice de inseguridad según NSE:</p>
<p>En base a los tests ANOVA, es posible observar diferencias estadísticamente significativas entre grupos de nivel socioeconómico, según su percepción de inseguridad y percepción de variación de la delincuencia. De tal manera, el NSE de cada persona influye de manera relevante en tales percepciones. En base a los resultados Tukey, podemos aseverar que a medida que aumenta el nivel socioeconómico, la percepción de inseguridad disminuye de manera consistente. Esto podría deberse a mejores condiciones de vida, entornos más protegidos o menor exposición a riesgos en los grupos con NSE alto.</p>
<p>Los resultados indican que las personas con un NSE bajo perciben mayor inseguridad, seguido de las de NSE medio, con el NSE alto mostrando significativamente menor percepción de inseguridad.</p>
<p>Respecto a las diferencias en Índice de percepción de delincuencia según NSE:</p>
<p>Aunque la percepción de aumento de delincuencia es ligeramente mayor en los NSE bajos y medios, las diferencias entre estos niveles no son significativas. Sin embargo, el NSE alto muestra una percepción significativamente menor.</p>
<p>En resumen y, en base a los tests ANOVA, es posible observar diferencias estadísticamente significativas entre grupos de nivel socioeconómico, según su percepción de inseguridad y percepción de variación de la delincuencia. Así, el NSE de cada persona influye de manera relevante en tales percepciones. En base a los resultados Tukey, podemos aseverar que a medida que aumenta el nivel socioeconómico, la percepción de inseguridad disminuye. Esto podría deberse a mejores condiciones de vida, entornos más protegidos o menor exposición a riesgos en los grupos con NSE alto.</p>
<p>En términos de magnitud, las mayores diferencias significativas se encuentran entre personas pertenecientes a NSE Alto, respecto a los grupos que se ubican en NSE Medio y NSE Bajo.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Anova para indice de inseguridad con nivel educacional</caption>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">Df</th>
<th style="text-align: right;">Sum Sq</th>
<th style="text-align: right;">Mean Sq</th>
<th style="text-align: right;">F value</th>
<th style="text-align: right;">Pr(&gt;F)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">factor(rph_nivel)</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">21.44736</td>
<td style="text-align: right;">7.1491213</td>
<td style="text-align: right;">43.58428</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Residuals</td>
<td style="text-align: right;">48460</td>
<td style="text-align: right;">7948.88464</td>
<td style="text-align: right;">0.1640298</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
</tbody>
</table>
</div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Anova para indice de delincuencia con nivel educacional</caption>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">Df</th>
<th style="text-align: right;">Sum Sq</th>
<th style="text-align: right;">Mean Sq</th>
<th style="text-align: right;">F value</th>
<th style="text-align: right;">Pr(&gt;F)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">factor(rph_nivel)</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">4.951451</td>
<td style="text-align: right;">1.6504838</td>
<td style="text-align: right;">11.22828</td>
<td style="text-align: right;">2e-07</td>
</tr>
<tr class="even">
<td style="text-align: left;">Residuals</td>
<td style="text-align: right;">48460</td>
<td style="text-align: right;">7123.306135</td>
<td style="text-align: right;">0.1469935</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
</tbody>
</table>
</div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Tukey para indice de inseguridad con nivel educacional</caption>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">diff</th>
<th style="text-align: right;">lwr</th>
<th style="text-align: right;">upr</th>
<th style="text-align: right;">p adj</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">2-1</td>
<td style="text-align: right;">-0.0164342</td>
<td style="text-align: right;">-0.0257249</td>
<td style="text-align: right;">-0.0071435</td>
<td style="text-align: right;">0.0001004</td>
</tr>
<tr class="even">
<td style="text-align: left;">3-1</td>
<td style="text-align: right;">-0.1217930</td>
<td style="text-align: right;">-0.1349832</td>
<td style="text-align: right;">-0.1086028</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3-2</td>
<td style="text-align: right;">-0.1053588</td>
<td style="text-align: right;">-0.1188557</td>
<td style="text-align: right;">-0.0918619</td>
<td style="text-align: right;">0.0000000</td>
</tr>
</tbody>
</table>
</div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Tukey para indice de delincuencia y nivel educacional</caption>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">diff</th>
<th style="text-align: right;">lwr</th>
<th style="text-align: right;">upr</th>
<th style="text-align: right;">p adj</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1-0</td>
<td style="text-align: right;">0.0125580</td>
<td style="text-align: right;">-0.0405374</td>
<td style="text-align: right;">0.0656533</td>
<td style="text-align: right;">0.9296980</td>
</tr>
<tr class="even">
<td style="text-align: left;">2-0</td>
<td style="text-align: right;">0.0247731</td>
<td style="text-align: right;">-0.0276283</td>
<td style="text-align: right;">0.0771745</td>
<td style="text-align: right;">0.6175805</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3-0</td>
<td style="text-align: right;">0.0025695</td>
<td style="text-align: right;">-0.0499446</td>
<td style="text-align: right;">0.0550836</td>
<td style="text-align: right;">0.9992908</td>
</tr>
<tr class="even">
<td style="text-align: left;">2-1</td>
<td style="text-align: right;">0.0122151</td>
<td style="text-align: right;">-0.0004462</td>
<td style="text-align: right;">0.0248765</td>
<td style="text-align: right;">0.0632898</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3-1</td>
<td style="text-align: right;">-0.0099885</td>
<td style="text-align: right;">-0.0231084</td>
<td style="text-align: right;">0.0031314</td>
<td style="text-align: right;">0.2049479</td>
</tr>
<tr class="even">
<td style="text-align: left;">3-2</td>
<td style="text-align: right;">-0.0222036</td>
<td style="text-align: right;">-0.0321497</td>
<td style="text-align: right;">-0.0122575</td>
<td style="text-align: right;">0.0000001</td>
</tr>
</tbody>
</table>
</div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Frecuencia y Proporción de rph_nivel</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Frecuencia.Var1</th>
<th style="text-align: right;">Frecuencia.Freq</th>
<th style="text-align: left;">Proporción.Var1</th>
<th style="text-align: right;">Proporción.Freq</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">0</td>
<td style="text-align: right;">359</td>
<td style="text-align: left;">0</td>
<td style="text-align: right;">0.740756</td>
</tr>
<tr class="even">
<td style="text-align: left;">1</td>
<td style="text-align: right;">8309</td>
<td style="text-align: left;">1</td>
<td style="text-align: right;">17.144685</td>
</tr>
<tr class="odd">
<td style="text-align: left;">2</td>
<td style="text-align: right;">22276</td>
<td style="text-align: left;">2</td>
<td style="text-align: right;">45.964014</td>
</tr>
<tr class="even">
<td style="text-align: left;">3</td>
<td style="text-align: right;">17520</td>
<td style="text-align: left;">3</td>
<td style="text-align: right;">36.150545</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Respecto a las diferencias en Índice de inseguridad según Nivel Educacional:</p>
<p>Las personas con educación secundaria tienen la percepción más alta de inseguridad, seguidas por quienes poseen educación básica y superior. Esto puede reflejar una exposición diferente a entornos sociales y económicos según el nivel educativo. Las personas con educación superior tienden a reportar menor percepción de inseguridad, lo que podría estar relacionado con mayor acceso a recursos, mejor calidad de vida o diferentes entornos habitacionales.</p>
<p>Más allá de lo anterior, en este caso, no es posible establecer que a medida que aumenta el nivel educacional, disminuye la percepción de inseguridad. Esto dado que las personas con educación secundaria muestran mayor percepción de este fenómeno, al compararlas con las personas que poseen educación básica o que no poseen estudios formales.</p>
<p>En relación a las diferencias en Índice de percepción de delincuencia según Nivel Educacional:</p>
<p>Las diferencias son menos marcadas, pero el nivel educacional también influye. Las personas con educación secundaria tienen una percepción ligeramente mayor de aumento en delincuencia, mientras que las personas con educación superior reportan valores más bajos.</p>
<p>Es importante destacar que la tendencia respecto a que existe menor inseguridad en personas que niveles educativos altos no se cumple al analizar a las personas que declaran nunca haber asistido, dado que, prácticamente, no se encontraron diferencias significativas entre este y los demás grupos. Es probable que este fenómeno se deba a la baja proporción de personas que no tienen educación formal en Chile, con lo que es muy difícil que la muestra de la encuesta analizada sea capaz de capturar, de manera representativa, la realidad social de las personas 365 personas de la encuesta (menos de un 1% de la muestra), que se encuentran en tal condición.</p>
</section>
</section>
<section id="análisis-de-componentes-principales-pca" class="level1">
<h1>Análisis de Componentes Principales (PCA)</h1>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Importancia de los Componentes Principales en Términos de Varianza Explicada</caption>
<colgroup>
<col style="width: 10%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 3%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 4%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">PC1</th>
<th style="text-align: right;">PC2</th>
<th style="text-align: right;">PC3</th>
<th style="text-align: right;">PC4</th>
<th style="text-align: right;">PC5</th>
<th style="text-align: right;">PC6</th>
<th style="text-align: right;">PC7</th>
<th style="text-align: right;">PC8</th>
<th style="text-align: right;">PC9</th>
<th style="text-align: right;">PC10</th>
<th style="text-align: right;">PC11</th>
<th style="text-align: right;">PC12</th>
<th style="text-align: right;">PC13</th>
<th style="text-align: right;">PC14</th>
<th style="text-align: right;">PC15</th>
<th style="text-align: right;">PC16</th>
<th style="text-align: right;">PC17</th>
<th style="text-align: right;">PC18</th>
<th style="text-align: right;">PC19</th>
<th style="text-align: right;">PC20</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Standard deviation</td>
<td style="text-align: right;">2.548693</td>
<td style="text-align: right;">1.207414</td>
<td style="text-align: right;">1.08032</td>
<td style="text-align: right;">1.020695</td>
<td style="text-align: right;">0.9757295</td>
<td style="text-align: right;">0.9211428</td>
<td style="text-align: right;">0.9175003</td>
<td style="text-align: right;">0.894584</td>
<td style="text-align: right;">0.8744588</td>
<td style="text-align: right;">0.8216779</td>
<td style="text-align: right;">0.8150634</td>
<td style="text-align: right;">0.8050118</td>
<td style="text-align: right;">0.7698587</td>
<td style="text-align: right;">0.7533629</td>
<td style="text-align: right;">0.7150804</td>
<td style="text-align: right;">0.7053284</td>
<td style="text-align: right;">0.6907073</td>
<td style="text-align: right;">0.6304276</td>
<td style="text-align: right;">0.550323</td>
<td style="text-align: right;">0.544174</td>
</tr>
<tr class="even">
<td style="text-align: left;">Proportion of Variance</td>
<td style="text-align: right;">0.324790</td>
<td style="text-align: right;">0.072890</td>
<td style="text-align: right;">0.05835</td>
<td style="text-align: right;">0.052090</td>
<td style="text-align: right;">0.0476000</td>
<td style="text-align: right;">0.0424300</td>
<td style="text-align: right;">0.0420900</td>
<td style="text-align: right;">0.040010</td>
<td style="text-align: right;">0.0382300</td>
<td style="text-align: right;">0.0337600</td>
<td style="text-align: right;">0.0332200</td>
<td style="text-align: right;">0.0324000</td>
<td style="text-align: right;">0.0296300</td>
<td style="text-align: right;">0.0283800</td>
<td style="text-align: right;">0.0255700</td>
<td style="text-align: right;">0.0248700</td>
<td style="text-align: right;">0.0238500</td>
<td style="text-align: right;">0.0198700</td>
<td style="text-align: right;">0.015140</td>
<td style="text-align: right;">0.014810</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Cumulative Proportion</td>
<td style="text-align: right;">0.324790</td>
<td style="text-align: right;">0.397680</td>
<td style="text-align: right;">0.45604</td>
<td style="text-align: right;">0.508130</td>
<td style="text-align: right;">0.5557300</td>
<td style="text-align: right;">0.5981600</td>
<td style="text-align: right;">0.6402500</td>
<td style="text-align: right;">0.680260</td>
<td style="text-align: right;">0.7185000</td>
<td style="text-align: right;">0.7522500</td>
<td style="text-align: right;">0.7854700</td>
<td style="text-align: right;">0.8178700</td>
<td style="text-align: right;">0.8475100</td>
<td style="text-align: right;">0.8758800</td>
<td style="text-align: right;">0.9014500</td>
<td style="text-align: right;">0.9263300</td>
<td style="text-align: right;">0.9501800</td>
<td style="text-align: right;">0.9700500</td>
<td style="text-align: right;">0.985190</td>
<td style="text-align: right;">1.000000</td>
</tr>
</tbody>
</table>
</div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Cargas de los Componentes Principales</caption>
<colgroup>
<col style="width: 7%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 4%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">PC1</th>
<th style="text-align: right;">PC2</th>
<th style="text-align: right;">PC3</th>
<th style="text-align: right;">PC4</th>
<th style="text-align: right;">PC5</th>
<th style="text-align: right;">PC6</th>
<th style="text-align: right;">PC7</th>
<th style="text-align: right;">PC8</th>
<th style="text-align: right;">PC9</th>
<th style="text-align: right;">PC10</th>
<th style="text-align: right;">PC11</th>
<th style="text-align: right;">PC12</th>
<th style="text-align: right;">PC13</th>
<th style="text-align: right;">PC14</th>
<th style="text-align: right;">PC15</th>
<th style="text-align: right;">PC16</th>
<th style="text-align: right;">PC17</th>
<th style="text-align: right;">PC18</th>
<th style="text-align: right;">PC19</th>
<th style="text-align: right;">PC20</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">P_INSEG_LUGARES_1</td>
<td style="text-align: right;">0.2157964</td>
<td style="text-align: right;">0.0536503</td>
<td style="text-align: right;">-0.1125831</td>
<td style="text-align: right;">-0.2020741</td>
<td style="text-align: right;">-0.0058772</td>
<td style="text-align: right;">0.3858033</td>
<td style="text-align: right;">-0.1681363</td>
<td style="text-align: right;">0.1422785</td>
<td style="text-align: right;">-0.5970927</td>
<td style="text-align: right;">0.3213639</td>
<td style="text-align: right;">0.1578958</td>
<td style="text-align: right;">0.1272512</td>
<td style="text-align: right;">-0.0121491</td>
<td style="text-align: right;">0.1445154</td>
<td style="text-align: right;">0.2040509</td>
<td style="text-align: right;">-0.3634357</td>
<td style="text-align: right;">-0.0216085</td>
<td style="text-align: right;">-0.0182185</td>
<td style="text-align: right;">0.0103875</td>
<td style="text-align: right;">0.0554366</td>
</tr>
<tr class="even">
<td style="text-align: left;">P_INSEG_LUGARES_2</td>
<td style="text-align: right;">0.2661339</td>
<td style="text-align: right;">0.2929062</td>
<td style="text-align: right;">-0.0708090</td>
<td style="text-align: right;">0.2822242</td>
<td style="text-align: right;">0.0723390</td>
<td style="text-align: right;">0.2040696</td>
<td style="text-align: right;">-0.0785814</td>
<td style="text-align: right;">-0.1948696</td>
<td style="text-align: right;">0.1470332</td>
<td style="text-align: right;">0.1650375</td>
<td style="text-align: right;">0.1186509</td>
<td style="text-align: right;">-0.1586913</td>
<td style="text-align: right;">-0.0799634</td>
<td style="text-align: right;">0.0125605</td>
<td style="text-align: right;">-0.1836194</td>
<td style="text-align: right;">-0.0488112</td>
<td style="text-align: right;">-0.2124675</td>
<td style="text-align: right;">0.0202985</td>
<td style="text-align: right;">-0.0084565</td>
<td style="text-align: right;">-0.7009238</td>
</tr>
<tr class="odd">
<td style="text-align: left;">P_INSEG_LUGARES_3</td>
<td style="text-align: right;">0.2626405</td>
<td style="text-align: right;">0.3044206</td>
<td style="text-align: right;">-0.0112374</td>
<td style="text-align: right;">0.3054837</td>
<td style="text-align: right;">0.0732640</td>
<td style="text-align: right;">0.1933047</td>
<td style="text-align: right;">-0.0675617</td>
<td style="text-align: right;">-0.2086390</td>
<td style="text-align: right;">0.1746109</td>
<td style="text-align: right;">0.1455454</td>
<td style="text-align: right;">0.0799172</td>
<td style="text-align: right;">-0.2023492</td>
<td style="text-align: right;">-0.0533093</td>
<td style="text-align: right;">0.0060811</td>
<td style="text-align: right;">-0.1335837</td>
<td style="text-align: right;">0.0393761</td>
<td style="text-align: right;">-0.1818948</td>
<td style="text-align: right;">0.0438422</td>
<td style="text-align: right;">0.0047487</td>
<td style="text-align: right;">0.7055237</td>
</tr>
<tr class="even">
<td style="text-align: left;">P_INSEG_LUGARES_4</td>
<td style="text-align: right;">0.2389838</td>
<td style="text-align: right;">0.1922286</td>
<td style="text-align: right;">0.2035953</td>
<td style="text-align: right;">0.3603096</td>
<td style="text-align: right;">-0.0314683</td>
<td style="text-align: right;">0.1235673</td>
<td style="text-align: right;">0.1120666</td>
<td style="text-align: right;">0.2522082</td>
<td style="text-align: right;">0.0574146</td>
<td style="text-align: right;">-0.0290055</td>
<td style="text-align: right;">0.0149639</td>
<td style="text-align: right;">-0.0838093</td>
<td style="text-align: right;">0.1068023</td>
<td style="text-align: right;">0.0468459</td>
<td style="text-align: right;">0.4287584</td>
<td style="text-align: right;">0.1555986</td>
<td style="text-align: right;">0.6336184</td>
<td style="text-align: right;">-0.0675970</td>
<td style="text-align: right;">0.0015831</td>
<td style="text-align: right;">-0.0561967</td>
</tr>
<tr class="odd">
<td style="text-align: left;">P_INSEG_LUGARES_5</td>
<td style="text-align: right;">0.1943993</td>
<td style="text-align: right;">0.0880904</td>
<td style="text-align: right;">0.3365147</td>
<td style="text-align: right;">0.2882916</td>
<td style="text-align: right;">-0.0820628</td>
<td style="text-align: right;">-0.0814421</td>
<td style="text-align: right;">0.2685393</td>
<td style="text-align: right;">0.5528972</td>
<td style="text-align: right;">-0.1778595</td>
<td style="text-align: right;">-0.2071972</td>
<td style="text-align: right;">-0.0685154</td>
<td style="text-align: right;">0.2369357</td>
<td style="text-align: right;">-0.0319771</td>
<td style="text-align: right;">-0.1128741</td>
<td style="text-align: right;">-0.2634831</td>
<td style="text-align: right;">-0.1362328</td>
<td style="text-align: right;">-0.3591930</td>
<td style="text-align: right;">0.0211085</td>
<td style="text-align: right;">-0.0090741</td>
<td style="text-align: right;">0.0151054</td>
</tr>
<tr class="even">
<td style="text-align: left;">P_INSEG_LUGARES_6</td>
<td style="text-align: right;">0.1568178</td>
<td style="text-align: right;">0.0196456</td>
<td style="text-align: right;">0.4111808</td>
<td style="text-align: right;">0.1095060</td>
<td style="text-align: right;">-0.1149171</td>
<td style="text-align: right;">-0.3659977</td>
<td style="text-align: right;">0.0425831</td>
<td style="text-align: right;">-0.5917669</td>
<td style="text-align: right;">-0.5165988</td>
<td style="text-align: right;">-0.1209950</td>
<td style="text-align: right;">0.0759197</td>
<td style="text-align: right;">-0.0508251</td>
<td style="text-align: right;">0.0341289</td>
<td style="text-align: right;">0.0135405</td>
<td style="text-align: right;">0.0113451</td>
<td style="text-align: right;">0.0315282</td>
<td style="text-align: right;">0.0417511</td>
<td style="text-align: right;">-0.0098613</td>
<td style="text-align: right;">-0.0110103</td>
<td style="text-align: right;">-0.0224895</td>
</tr>
<tr class="odd">
<td style="text-align: left;">P_INSEG_LUGARES_7</td>
<td style="text-align: right;">0.2400279</td>
<td style="text-align: right;">0.0208745</td>
<td style="text-align: right;">0.1481601</td>
<td style="text-align: right;">-0.2439320</td>
<td style="text-align: right;">-0.0471443</td>
<td style="text-align: right;">-0.0641888</td>
<td style="text-align: right;">-0.1000183</td>
<td style="text-align: right;">0.0925939</td>
<td style="text-align: right;">0.0024076</td>
<td style="text-align: right;">0.0043514</td>
<td style="text-align: right;">-0.5303705</td>
<td style="text-align: right;">-0.2704079</td>
<td style="text-align: right;">-0.6230110</td>
<td style="text-align: right;">0.2964573</td>
<td style="text-align: right;">-0.0030712</td>
<td style="text-align: right;">0.0566700</td>
<td style="text-align: right;">0.0340952</td>
<td style="text-align: right;">0.0200244</td>
<td style="text-align: right;">-0.0102318</td>
<td style="text-align: right;">-0.0148251</td>
</tr>
<tr class="even">
<td style="text-align: left;">P_INSEG_LUGARES_8</td>
<td style="text-align: right;">0.2217692</td>
<td style="text-align: right;">0.2379833</td>
<td style="text-align: right;">0.0568843</td>
<td style="text-align: right;">-0.1084432</td>
<td style="text-align: right;">-0.0173396</td>
<td style="text-align: right;">0.0176973</td>
<td style="text-align: right;">-0.2122945</td>
<td style="text-align: right;">-0.2119610</td>
<td style="text-align: right;">0.2157050</td>
<td style="text-align: right;">-0.0586124</td>
<td style="text-align: right;">-0.5226611</td>
<td style="text-align: right;">0.5367062</td>
<td style="text-align: right;">0.3702990</td>
<td style="text-align: right;">0.0458647</td>
<td style="text-align: right;">0.1401995</td>
<td style="text-align: right;">-0.1126921</td>
<td style="text-align: right;">-0.0689937</td>
<td style="text-align: right;">-0.0134420</td>
<td style="text-align: right;">0.0281713</td>
<td style="text-align: right;">-0.0083222</td>
</tr>
<tr class="odd">
<td style="text-align: left;">P_INSEG_LUGARES_9</td>
<td style="text-align: right;">0.1768285</td>
<td style="text-align: right;">-0.1515539</td>
<td style="text-align: right;">0.4270370</td>
<td style="text-align: right;">-0.2238901</td>
<td style="text-align: right;">-0.0857104</td>
<td style="text-align: right;">-0.2479846</td>
<td style="text-align: right;">-0.0217320</td>
<td style="text-align: right;">0.0924940</td>
<td style="text-align: right;">0.3067728</td>
<td style="text-align: right;">0.6511951</td>
<td style="text-align: right;">0.2623207</td>
<td style="text-align: right;">0.1514827</td>
<td style="text-align: right;">0.0475953</td>
<td style="text-align: right;">0.0455320</td>
<td style="text-align: right;">-0.1235219</td>
<td style="text-align: right;">0.0417379</td>
<td style="text-align: right;">0.0596891</td>
<td style="text-align: right;">0.0126483</td>
<td style="text-align: right;">0.0205027</td>
<td style="text-align: right;">0.0008488</td>
</tr>
<tr class="even">
<td style="text-align: left;">P_INSEG_LUGARES_10</td>
<td style="text-align: right;">0.2469247</td>
<td style="text-align: right;">-0.0056502</td>
<td style="text-align: right;">0.1489242</td>
<td style="text-align: right;">-0.2884189</td>
<td style="text-align: right;">-0.0609072</td>
<td style="text-align: right;">-0.0253564</td>
<td style="text-align: right;">-0.1727670</td>
<td style="text-align: right;">0.0301930</td>
<td style="text-align: right;">0.1734442</td>
<td style="text-align: right;">-0.2153234</td>
<td style="text-align: right;">0.0880219</td>
<td style="text-align: right;">-0.3263835</td>
<td style="text-align: right;">0.0020451</td>
<td style="text-align: right;">-0.6528967</td>
<td style="text-align: right;">0.2390083</td>
<td style="text-align: right;">-0.3479214</td>
<td style="text-align: right;">-0.0551911</td>
<td style="text-align: right;">-0.0101415</td>
<td style="text-align: right;">-0.0139390</td>
<td style="text-align: right;">-0.0017093</td>
</tr>
<tr class="odd">
<td style="text-align: left;">P_INSEG_LUGARES_11</td>
<td style="text-align: right;">0.2509760</td>
<td style="text-align: right;">0.1256376</td>
<td style="text-align: right;">-0.0637152</td>
<td style="text-align: right;">-0.3275802</td>
<td style="text-align: right;">-0.0032745</td>
<td style="text-align: right;">0.1453532</td>
<td style="text-align: right;">-0.1613713</td>
<td style="text-align: right;">0.1349023</td>
<td style="text-align: right;">-0.2419065</td>
<td style="text-align: right;">-0.0656050</td>
<td style="text-align: right;">-0.0035995</td>
<td style="text-align: right;">-0.0404540</td>
<td style="text-align: right;">0.2173356</td>
<td style="text-align: right;">-0.2423175</td>
<td style="text-align: right;">-0.3262067</td>
<td style="text-align: right;">0.6798110</td>
<td style="text-align: right;">0.0684578</td>
<td style="text-align: right;">0.0147142</td>
<td style="text-align: right;">0.0040020</td>
<td style="text-align: right;">-0.0241377</td>
</tr>
<tr class="even">
<td style="text-align: left;">P_INSEG_LUGARES_12</td>
<td style="text-align: right;">0.2618466</td>
<td style="text-align: right;">0.0415259</td>
<td style="text-align: right;">-0.3128227</td>
<td style="text-align: right;">-0.0848598</td>
<td style="text-align: right;">0.0842756</td>
<td style="text-align: right;">-0.2845045</td>
<td style="text-align: right;">0.2090896</td>
<td style="text-align: right;">0.0376968</td>
<td style="text-align: right;">-0.0059859</td>
<td style="text-align: right;">0.0107496</td>
<td style="text-align: right;">-0.0662910</td>
<td style="text-align: right;">-0.1661336</td>
<td style="text-align: right;">0.2002458</td>
<td style="text-align: right;">0.1005071</td>
<td style="text-align: right;">-0.3370898</td>
<td style="text-align: right;">-0.2802359</td>
<td style="text-align: right;">0.2200098</td>
<td style="text-align: right;">-0.6059584</td>
<td style="text-align: right;">0.0074020</td>
<td style="text-align: right;">0.0362687</td>
</tr>
<tr class="odd">
<td style="text-align: left;">P_INSEG_LUGARES_13</td>
<td style="text-align: right;">0.2641170</td>
<td style="text-align: right;">-0.0474852</td>
<td style="text-align: right;">-0.2408565</td>
<td style="text-align: right;">-0.0889692</td>
<td style="text-align: right;">0.0620645</td>
<td style="text-align: right;">-0.2612544</td>
<td style="text-align: right;">0.2696155</td>
<td style="text-align: right;">0.0871146</td>
<td style="text-align: right;">-0.0170756</td>
<td style="text-align: right;">0.0302529</td>
<td style="text-align: right;">-0.0641958</td>
<td style="text-align: right;">-0.2827782</td>
<td style="text-align: right;">0.3596706</td>
<td style="text-align: right;">0.2134343</td>
<td style="text-align: right;">0.1117013</td>
<td style="text-align: right;">-0.0625461</td>
<td style="text-align: right;">-0.0869310</td>
<td style="text-align: right;">0.6507506</td>
<td style="text-align: right;">-0.0426690</td>
<td style="text-align: right;">-0.0148620</td>
</tr>
<tr class="even">
<td style="text-align: left;">P_INSEG_LUGARES_14</td>
<td style="text-align: right;">0.1387053</td>
<td style="text-align: right;">-0.2714354</td>
<td style="text-align: right;">0.1336111</td>
<td style="text-align: right;">-0.1864405</td>
<td style="text-align: right;">0.0346138</td>
<td style="text-align: right;">0.5132506</td>
<td style="text-align: right;">0.6905290</td>
<td style="text-align: right;">-0.2775966</td>
<td style="text-align: right;">0.0745843</td>
<td style="text-align: right;">0.0105107</td>
<td style="text-align: right;">-0.1188999</td>
<td style="text-align: right;">0.0535416</td>
<td style="text-align: right;">-0.0261929</td>
<td style="text-align: right;">-0.0998551</td>
<td style="text-align: right;">-0.0339695</td>
<td style="text-align: right;">0.0165590</td>
<td style="text-align: right;">0.0137940</td>
<td style="text-align: right;">-0.0281409</td>
<td style="text-align: right;">0.0128444</td>
<td style="text-align: right;">-0.0069037</td>
</tr>
<tr class="odd">
<td style="text-align: left;">P_INSEG_LUGARES_15</td>
<td style="text-align: right;">0.0689426</td>
<td style="text-align: right;">-0.1968650</td>
<td style="text-align: right;">0.1774966</td>
<td style="text-align: right;">0.0494589</td>
<td style="text-align: right;">0.9455430</td>
<td style="text-align: right;">-0.0400391</td>
<td style="text-align: right;">-0.1267231</td>
<td style="text-align: right;">0.0265573</td>
<td style="text-align: right;">-0.0585804</td>
<td style="text-align: right;">-0.0324796</td>
<td style="text-align: right;">-0.0289275</td>
<td style="text-align: right;">0.0472584</td>
<td style="text-align: right;">-0.0126286</td>
<td style="text-align: right;">-0.0372642</td>
<td style="text-align: right;">0.0068668</td>
<td style="text-align: right;">-0.0013634</td>
<td style="text-align: right;">0.0272799</td>
<td style="text-align: right;">0.0122713</td>
<td style="text-align: right;">0.0062295</td>
<td style="text-align: right;">-0.0058077</td>
</tr>
<tr class="even">
<td style="text-align: left;">P_INSEG_LUGARES_16</td>
<td style="text-align: right;">0.2348098</td>
<td style="text-align: right;">-0.0446012</td>
<td style="text-align: right;">0.1075544</td>
<td style="text-align: right;">-0.2393203</td>
<td style="text-align: right;">-0.0145288</td>
<td style="text-align: right;">0.1064062</td>
<td style="text-align: right;">-0.0966587</td>
<td style="text-align: right;">-0.0026392</td>
<td style="text-align: right;">0.2242272</td>
<td style="text-align: right;">-0.5402522</td>
<td style="text-align: right;">0.4870978</td>
<td style="text-align: right;">0.0990046</td>
<td style="text-align: right;">-0.0118925</td>
<td style="text-align: right;">0.5047918</td>
<td style="text-align: right;">0.0123224</td>
<td style="text-align: right;">0.0056676</td>
<td style="text-align: right;">-0.0702924</td>
<td style="text-align: right;">-0.0561648</td>
<td style="text-align: right;">-0.0240324</td>
<td style="text-align: right;">0.0109610</td>
</tr>
<tr class="odd">
<td style="text-align: left;">P_INSEG_OSCURO_1</td>
<td style="text-align: right;">0.2483277</td>
<td style="text-align: right;">0.0443373</td>
<td style="text-align: right;">-0.3442051</td>
<td style="text-align: right;">0.0228917</td>
<td style="text-align: right;">0.0159855</td>
<td style="text-align: right;">-0.1761807</td>
<td style="text-align: right;">0.0748215</td>
<td style="text-align: right;">-0.0994465</td>
<td style="text-align: right;">0.0252169</td>
<td style="text-align: right;">-0.0557077</td>
<td style="text-align: right;">0.1645211</td>
<td style="text-align: right;">0.4643948</td>
<td style="text-align: right;">-0.4346487</td>
<td style="text-align: right;">-0.2417019</td>
<td style="text-align: right;">-0.1237060</td>
<td style="text-align: right;">-0.0561232</td>
<td style="text-align: right;">0.3260346</td>
<td style="text-align: right;">0.2709853</td>
<td style="text-align: right;">-0.2781154</td>
<td style="text-align: right;">0.0352469</td>
</tr>
<tr class="even">
<td style="text-align: left;">P_INSEG_DIA_1</td>
<td style="text-align: right;">0.2655338</td>
<td style="text-align: right;">-0.1259464</td>
<td style="text-align: right;">-0.2836873</td>
<td style="text-align: right;">0.0672073</td>
<td style="text-align: right;">0.0159770</td>
<td style="text-align: right;">-0.2354978</td>
<td style="text-align: right;">0.1406690</td>
<td style="text-align: right;">0.0069812</td>
<td style="text-align: right;">-0.0024924</td>
<td style="text-align: right;">0.0821052</td>
<td style="text-align: right;">0.0828915</td>
<td style="text-align: right;">0.1327323</td>
<td style="text-align: right;">-0.1630365</td>
<td style="text-align: right;">-0.0722142</td>
<td style="text-align: right;">0.4995340</td>
<td style="text-align: right;">0.3380373</td>
<td style="text-align: right;">-0.3897162</td>
<td style="text-align: right;">-0.2773406</td>
<td style="text-align: right;">0.3120504</td>
<td style="text-align: right;">-0.0086877</td>
</tr>
<tr class="odd">
<td style="text-align: left;">P_INSEG_OSCURO_2</td>
<td style="text-align: right;">0.2070312</td>
<td style="text-align: right;">-0.4992377</td>
<td style="text-align: right;">-0.0786015</td>
<td style="text-align: right;">0.2588722</td>
<td style="text-align: right;">-0.1645681</td>
<td style="text-align: right;">0.0988576</td>
<td style="text-align: right;">-0.2640282</td>
<td style="text-align: right;">-0.0287870</td>
<td style="text-align: right;">0.0079567</td>
<td style="text-align: right;">-0.0813742</td>
<td style="text-align: right;">-0.0678442</td>
<td style="text-align: right;">0.0236476</td>
<td style="text-align: right;">0.0146989</td>
<td style="text-align: right;">-0.0259264</td>
<td style="text-align: right;">-0.2450668</td>
<td style="text-align: right;">-0.1072158</td>
<td style="text-align: right;">0.1901195</td>
<td style="text-align: right;">0.1602102</td>
<td style="text-align: right;">0.6173904</td>
<td style="text-align: right;">0.0063149</td>
</tr>
<tr class="even">
<td style="text-align: left;">P_INSEG_DIA_2</td>
<td style="text-align: right;">0.1990436</td>
<td style="text-align: right;">-0.5405856</td>
<td style="text-align: right;">-0.0520343</td>
<td style="text-align: right;">0.2602540</td>
<td style="text-align: right;">-0.1443467</td>
<td style="text-align: right;">0.0822719</td>
<td style="text-align: right;">-0.2221059</td>
<td style="text-align: right;">0.0066644</td>
<td style="text-align: right;">0.0041364</td>
<td style="text-align: right;">0.0343521</td>
<td style="text-align: right;">-0.1165620</td>
<td style="text-align: right;">-0.0578284</td>
<td style="text-align: right;">0.1268434</td>
<td style="text-align: right;">0.0246880</td>
<td style="text-align: right;">0.0510223</td>
<td style="text-align: right;">0.0877785</td>
<td style="text-align: right;">-0.1252697</td>
<td style="text-align: right;">-0.1427714</td>
<td style="text-align: right;">-0.6629568</td>
<td style="text-align: right;">0.0024683</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Como podemos observar, los resultados muestran que los primeros 4 componentes explican el 50.8% de la varianza total:</p>
<p>PC1: 32.52% - Captura un patrón generalizado de percepción de inseguridad. PC2: 7.28% - Refleja inseguridades específicas en lugares de la vida mayormente privada, como las viviendas de las personas y sus respectivos lugares de trabajo. PC3: 5.83% - Representa variaciones relacionadas con percepción de temor por permanencia en terminales de transporte público. PC4: 5.19% - Representa variaciones relacionadas con temor en traslados de transporte público</p>
<p>Una vez que tenemos indicios de posibles componentes a retener, creamos un Screen Plot para visualizar la varianza explicada por cada componente principal.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/varianza-pca-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Componentes retenidos en el Análisis de Componentes Principales</caption>
<thead>
<tr class="header">
<th style="text-align: left;">PC</th>
<th style="text-align: right;">Eigenvalue</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">PC1</td>
<td style="text-align: right;">6.495837</td>
</tr>
<tr class="even">
<td style="text-align: left;">PC2</td>
<td style="text-align: right;">1.457848</td>
</tr>
<tr class="odd">
<td style="text-align: left;">PC3</td>
<td style="text-align: right;">1.167090</td>
</tr>
<tr class="even">
<td style="text-align: left;">PC4</td>
<td style="text-align: right;">1.041818</td>
</tr>
</tbody>
</table>
</div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Cargas de las variables en los componentes principales</caption>
<colgroup>
<col style="width: 12%">
<col style="width: 3%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 4%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">PC1</th>
<th style="text-align: right;">PC2</th>
<th style="text-align: right;">PC3</th>
<th style="text-align: right;">PC4</th>
<th style="text-align: right;">PC5</th>
<th style="text-align: right;">PC6</th>
<th style="text-align: right;">PC7</th>
<th style="text-align: right;">PC8</th>
<th style="text-align: right;">PC9</th>
<th style="text-align: right;">PC10</th>
<th style="text-align: right;">PC11</th>
<th style="text-align: right;">PC12</th>
<th style="text-align: right;">PC13</th>
<th style="text-align: right;">PC14</th>
<th style="text-align: right;">PC15</th>
<th style="text-align: right;">PC16</th>
<th style="text-align: right;">PC17</th>
<th style="text-align: right;">PC18</th>
<th style="text-align: right;">PC19</th>
<th style="text-align: right;">PC20</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">P_INSEG_LUGARES_1</td>
<td style="text-align: right;">0.216</td>
<td style="text-align: right;">0.054</td>
<td style="text-align: right;">-0.113</td>
<td style="text-align: right;">-0.202</td>
<td style="text-align: right;">-0.006</td>
<td style="text-align: right;">0.386</td>
<td style="text-align: right;">-0.168</td>
<td style="text-align: right;">0.142</td>
<td style="text-align: right;">-0.597</td>
<td style="text-align: right;">0.321</td>
<td style="text-align: right;">0.158</td>
<td style="text-align: right;">0.127</td>
<td style="text-align: right;">-0.012</td>
<td style="text-align: right;">0.145</td>
<td style="text-align: right;">0.204</td>
<td style="text-align: right;">-0.363</td>
<td style="text-align: right;">-0.022</td>
<td style="text-align: right;">-0.018</td>
<td style="text-align: right;">0.010</td>
<td style="text-align: right;">0.055</td>
</tr>
<tr class="even">
<td style="text-align: left;">P_INSEG_LUGARES_2</td>
<td style="text-align: right;">0.266</td>
<td style="text-align: right;">0.293</td>
<td style="text-align: right;">-0.071</td>
<td style="text-align: right;">0.282</td>
<td style="text-align: right;">0.072</td>
<td style="text-align: right;">0.204</td>
<td style="text-align: right;">-0.079</td>
<td style="text-align: right;">-0.195</td>
<td style="text-align: right;">0.147</td>
<td style="text-align: right;">0.165</td>
<td style="text-align: right;">0.119</td>
<td style="text-align: right;">-0.159</td>
<td style="text-align: right;">-0.080</td>
<td style="text-align: right;">0.013</td>
<td style="text-align: right;">-0.184</td>
<td style="text-align: right;">-0.049</td>
<td style="text-align: right;">-0.212</td>
<td style="text-align: right;">0.020</td>
<td style="text-align: right;">-0.008</td>
<td style="text-align: right;">-0.701</td>
</tr>
<tr class="odd">
<td style="text-align: left;">P_INSEG_LUGARES_3</td>
<td style="text-align: right;">0.263</td>
<td style="text-align: right;">0.304</td>
<td style="text-align: right;">-0.011</td>
<td style="text-align: right;">0.305</td>
<td style="text-align: right;">0.073</td>
<td style="text-align: right;">0.193</td>
<td style="text-align: right;">-0.068</td>
<td style="text-align: right;">-0.209</td>
<td style="text-align: right;">0.175</td>
<td style="text-align: right;">0.146</td>
<td style="text-align: right;">0.080</td>
<td style="text-align: right;">-0.202</td>
<td style="text-align: right;">-0.053</td>
<td style="text-align: right;">0.006</td>
<td style="text-align: right;">-0.134</td>
<td style="text-align: right;">0.039</td>
<td style="text-align: right;">-0.182</td>
<td style="text-align: right;">0.044</td>
<td style="text-align: right;">0.005</td>
<td style="text-align: right;">0.706</td>
</tr>
<tr class="even">
<td style="text-align: left;">P_INSEG_LUGARES_4</td>
<td style="text-align: right;">0.239</td>
<td style="text-align: right;">0.192</td>
<td style="text-align: right;">0.204</td>
<td style="text-align: right;">0.360</td>
<td style="text-align: right;">-0.031</td>
<td style="text-align: right;">0.124</td>
<td style="text-align: right;">0.112</td>
<td style="text-align: right;">0.252</td>
<td style="text-align: right;">0.057</td>
<td style="text-align: right;">-0.029</td>
<td style="text-align: right;">0.015</td>
<td style="text-align: right;">-0.084</td>
<td style="text-align: right;">0.107</td>
<td style="text-align: right;">0.047</td>
<td style="text-align: right;">0.429</td>
<td style="text-align: right;">0.156</td>
<td style="text-align: right;">0.634</td>
<td style="text-align: right;">-0.068</td>
<td style="text-align: right;">0.002</td>
<td style="text-align: right;">-0.056</td>
</tr>
<tr class="odd">
<td style="text-align: left;">P_INSEG_LUGARES_5</td>
<td style="text-align: right;">0.194</td>
<td style="text-align: right;">0.088</td>
<td style="text-align: right;">0.337</td>
<td style="text-align: right;">0.288</td>
<td style="text-align: right;">-0.082</td>
<td style="text-align: right;">-0.081</td>
<td style="text-align: right;">0.269</td>
<td style="text-align: right;">0.553</td>
<td style="text-align: right;">-0.178</td>
<td style="text-align: right;">-0.207</td>
<td style="text-align: right;">-0.069</td>
<td style="text-align: right;">0.237</td>
<td style="text-align: right;">-0.032</td>
<td style="text-align: right;">-0.113</td>
<td style="text-align: right;">-0.263</td>
<td style="text-align: right;">-0.136</td>
<td style="text-align: right;">-0.359</td>
<td style="text-align: right;">0.021</td>
<td style="text-align: right;">-0.009</td>
<td style="text-align: right;">0.015</td>
</tr>
<tr class="even">
<td style="text-align: left;">P_INSEG_LUGARES_6</td>
<td style="text-align: right;">0.157</td>
<td style="text-align: right;">0.020</td>
<td style="text-align: right;">0.411</td>
<td style="text-align: right;">0.110</td>
<td style="text-align: right;">-0.115</td>
<td style="text-align: right;">-0.366</td>
<td style="text-align: right;">0.043</td>
<td style="text-align: right;">-0.592</td>
<td style="text-align: right;">-0.517</td>
<td style="text-align: right;">-0.121</td>
<td style="text-align: right;">0.076</td>
<td style="text-align: right;">-0.051</td>
<td style="text-align: right;">0.034</td>
<td style="text-align: right;">0.014</td>
<td style="text-align: right;">0.011</td>
<td style="text-align: right;">0.032</td>
<td style="text-align: right;">0.042</td>
<td style="text-align: right;">-0.010</td>
<td style="text-align: right;">-0.011</td>
<td style="text-align: right;">-0.022</td>
</tr>
<tr class="odd">
<td style="text-align: left;">P_INSEG_LUGARES_7</td>
<td style="text-align: right;">0.240</td>
<td style="text-align: right;">0.021</td>
<td style="text-align: right;">0.148</td>
<td style="text-align: right;">-0.244</td>
<td style="text-align: right;">-0.047</td>
<td style="text-align: right;">-0.064</td>
<td style="text-align: right;">-0.100</td>
<td style="text-align: right;">0.093</td>
<td style="text-align: right;">0.002</td>
<td style="text-align: right;">0.004</td>
<td style="text-align: right;">-0.530</td>
<td style="text-align: right;">-0.270</td>
<td style="text-align: right;">-0.623</td>
<td style="text-align: right;">0.296</td>
<td style="text-align: right;">-0.003</td>
<td style="text-align: right;">0.057</td>
<td style="text-align: right;">0.034</td>
<td style="text-align: right;">0.020</td>
<td style="text-align: right;">-0.010</td>
<td style="text-align: right;">-0.015</td>
</tr>
<tr class="even">
<td style="text-align: left;">P_INSEG_LUGARES_8</td>
<td style="text-align: right;">0.222</td>
<td style="text-align: right;">0.238</td>
<td style="text-align: right;">0.057</td>
<td style="text-align: right;">-0.108</td>
<td style="text-align: right;">-0.017</td>
<td style="text-align: right;">0.018</td>
<td style="text-align: right;">-0.212</td>
<td style="text-align: right;">-0.212</td>
<td style="text-align: right;">0.216</td>
<td style="text-align: right;">-0.059</td>
<td style="text-align: right;">-0.523</td>
<td style="text-align: right;">0.537</td>
<td style="text-align: right;">0.370</td>
<td style="text-align: right;">0.046</td>
<td style="text-align: right;">0.140</td>
<td style="text-align: right;">-0.113</td>
<td style="text-align: right;">-0.069</td>
<td style="text-align: right;">-0.013</td>
<td style="text-align: right;">0.028</td>
<td style="text-align: right;">-0.008</td>
</tr>
<tr class="odd">
<td style="text-align: left;">P_INSEG_LUGARES_9</td>
<td style="text-align: right;">0.177</td>
<td style="text-align: right;">-0.152</td>
<td style="text-align: right;">0.427</td>
<td style="text-align: right;">-0.224</td>
<td style="text-align: right;">-0.086</td>
<td style="text-align: right;">-0.248</td>
<td style="text-align: right;">-0.022</td>
<td style="text-align: right;">0.092</td>
<td style="text-align: right;">0.307</td>
<td style="text-align: right;">0.651</td>
<td style="text-align: right;">0.262</td>
<td style="text-align: right;">0.151</td>
<td style="text-align: right;">0.048</td>
<td style="text-align: right;">0.046</td>
<td style="text-align: right;">-0.124</td>
<td style="text-align: right;">0.042</td>
<td style="text-align: right;">0.060</td>
<td style="text-align: right;">0.013</td>
<td style="text-align: right;">0.021</td>
<td style="text-align: right;">0.001</td>
</tr>
<tr class="even">
<td style="text-align: left;">P_INSEG_LUGARES_10</td>
<td style="text-align: right;">0.247</td>
<td style="text-align: right;">-0.006</td>
<td style="text-align: right;">0.149</td>
<td style="text-align: right;">-0.288</td>
<td style="text-align: right;">-0.061</td>
<td style="text-align: right;">-0.025</td>
<td style="text-align: right;">-0.173</td>
<td style="text-align: right;">0.030</td>
<td style="text-align: right;">0.173</td>
<td style="text-align: right;">-0.215</td>
<td style="text-align: right;">0.088</td>
<td style="text-align: right;">-0.326</td>
<td style="text-align: right;">0.002</td>
<td style="text-align: right;">-0.653</td>
<td style="text-align: right;">0.239</td>
<td style="text-align: right;">-0.348</td>
<td style="text-align: right;">-0.055</td>
<td style="text-align: right;">-0.010</td>
<td style="text-align: right;">-0.014</td>
<td style="text-align: right;">-0.002</td>
</tr>
<tr class="odd">
<td style="text-align: left;">P_INSEG_LUGARES_11</td>
<td style="text-align: right;">0.251</td>
<td style="text-align: right;">0.126</td>
<td style="text-align: right;">-0.064</td>
<td style="text-align: right;">-0.328</td>
<td style="text-align: right;">-0.003</td>
<td style="text-align: right;">0.145</td>
<td style="text-align: right;">-0.161</td>
<td style="text-align: right;">0.135</td>
<td style="text-align: right;">-0.242</td>
<td style="text-align: right;">-0.066</td>
<td style="text-align: right;">-0.004</td>
<td style="text-align: right;">-0.040</td>
<td style="text-align: right;">0.217</td>
<td style="text-align: right;">-0.242</td>
<td style="text-align: right;">-0.326</td>
<td style="text-align: right;">0.680</td>
<td style="text-align: right;">0.068</td>
<td style="text-align: right;">0.015</td>
<td style="text-align: right;">0.004</td>
<td style="text-align: right;">-0.024</td>
</tr>
<tr class="even">
<td style="text-align: left;">P_INSEG_LUGARES_12</td>
<td style="text-align: right;">0.262</td>
<td style="text-align: right;">0.042</td>
<td style="text-align: right;">-0.313</td>
<td style="text-align: right;">-0.085</td>
<td style="text-align: right;">0.084</td>
<td style="text-align: right;">-0.285</td>
<td style="text-align: right;">0.209</td>
<td style="text-align: right;">0.038</td>
<td style="text-align: right;">-0.006</td>
<td style="text-align: right;">0.011</td>
<td style="text-align: right;">-0.066</td>
<td style="text-align: right;">-0.166</td>
<td style="text-align: right;">0.200</td>
<td style="text-align: right;">0.101</td>
<td style="text-align: right;">-0.337</td>
<td style="text-align: right;">-0.280</td>
<td style="text-align: right;">0.220</td>
<td style="text-align: right;">-0.606</td>
<td style="text-align: right;">0.007</td>
<td style="text-align: right;">0.036</td>
</tr>
<tr class="odd">
<td style="text-align: left;">P_INSEG_LUGARES_13</td>
<td style="text-align: right;">0.264</td>
<td style="text-align: right;">-0.047</td>
<td style="text-align: right;">-0.241</td>
<td style="text-align: right;">-0.089</td>
<td style="text-align: right;">0.062</td>
<td style="text-align: right;">-0.261</td>
<td style="text-align: right;">0.270</td>
<td style="text-align: right;">0.087</td>
<td style="text-align: right;">-0.017</td>
<td style="text-align: right;">0.030</td>
<td style="text-align: right;">-0.064</td>
<td style="text-align: right;">-0.283</td>
<td style="text-align: right;">0.360</td>
<td style="text-align: right;">0.213</td>
<td style="text-align: right;">0.112</td>
<td style="text-align: right;">-0.063</td>
<td style="text-align: right;">-0.087</td>
<td style="text-align: right;">0.651</td>
<td style="text-align: right;">-0.043</td>
<td style="text-align: right;">-0.015</td>
</tr>
<tr class="even">
<td style="text-align: left;">P_INSEG_LUGARES_14</td>
<td style="text-align: right;">0.139</td>
<td style="text-align: right;">-0.271</td>
<td style="text-align: right;">0.134</td>
<td style="text-align: right;">-0.186</td>
<td style="text-align: right;">0.035</td>
<td style="text-align: right;">0.513</td>
<td style="text-align: right;">0.691</td>
<td style="text-align: right;">-0.278</td>
<td style="text-align: right;">0.075</td>
<td style="text-align: right;">0.011</td>
<td style="text-align: right;">-0.119</td>
<td style="text-align: right;">0.054</td>
<td style="text-align: right;">-0.026</td>
<td style="text-align: right;">-0.100</td>
<td style="text-align: right;">-0.034</td>
<td style="text-align: right;">0.017</td>
<td style="text-align: right;">0.014</td>
<td style="text-align: right;">-0.028</td>
<td style="text-align: right;">0.013</td>
<td style="text-align: right;">-0.007</td>
</tr>
<tr class="odd">
<td style="text-align: left;">P_INSEG_LUGARES_15</td>
<td style="text-align: right;">0.069</td>
<td style="text-align: right;">-0.197</td>
<td style="text-align: right;">0.177</td>
<td style="text-align: right;">0.049</td>
<td style="text-align: right;">0.946</td>
<td style="text-align: right;">-0.040</td>
<td style="text-align: right;">-0.127</td>
<td style="text-align: right;">0.027</td>
<td style="text-align: right;">-0.059</td>
<td style="text-align: right;">-0.032</td>
<td style="text-align: right;">-0.029</td>
<td style="text-align: right;">0.047</td>
<td style="text-align: right;">-0.013</td>
<td style="text-align: right;">-0.037</td>
<td style="text-align: right;">0.007</td>
<td style="text-align: right;">-0.001</td>
<td style="text-align: right;">0.027</td>
<td style="text-align: right;">0.012</td>
<td style="text-align: right;">0.006</td>
<td style="text-align: right;">-0.006</td>
</tr>
<tr class="even">
<td style="text-align: left;">P_INSEG_LUGARES_16</td>
<td style="text-align: right;">0.235</td>
<td style="text-align: right;">-0.045</td>
<td style="text-align: right;">0.108</td>
<td style="text-align: right;">-0.239</td>
<td style="text-align: right;">-0.015</td>
<td style="text-align: right;">0.106</td>
<td style="text-align: right;">-0.097</td>
<td style="text-align: right;">-0.003</td>
<td style="text-align: right;">0.224</td>
<td style="text-align: right;">-0.540</td>
<td style="text-align: right;">0.487</td>
<td style="text-align: right;">0.099</td>
<td style="text-align: right;">-0.012</td>
<td style="text-align: right;">0.505</td>
<td style="text-align: right;">0.012</td>
<td style="text-align: right;">0.006</td>
<td style="text-align: right;">-0.070</td>
<td style="text-align: right;">-0.056</td>
<td style="text-align: right;">-0.024</td>
<td style="text-align: right;">0.011</td>
</tr>
<tr class="odd">
<td style="text-align: left;">P_INSEG_OSCURO_1</td>
<td style="text-align: right;">0.248</td>
<td style="text-align: right;">0.044</td>
<td style="text-align: right;">-0.344</td>
<td style="text-align: right;">0.023</td>
<td style="text-align: right;">0.016</td>
<td style="text-align: right;">-0.176</td>
<td style="text-align: right;">0.075</td>
<td style="text-align: right;">-0.099</td>
<td style="text-align: right;">0.025</td>
<td style="text-align: right;">-0.056</td>
<td style="text-align: right;">0.165</td>
<td style="text-align: right;">0.464</td>
<td style="text-align: right;">-0.435</td>
<td style="text-align: right;">-0.242</td>
<td style="text-align: right;">-0.124</td>
<td style="text-align: right;">-0.056</td>
<td style="text-align: right;">0.326</td>
<td style="text-align: right;">0.271</td>
<td style="text-align: right;">-0.278</td>
<td style="text-align: right;">0.035</td>
</tr>
<tr class="even">
<td style="text-align: left;">P_INSEG_DIA_1</td>
<td style="text-align: right;">0.266</td>
<td style="text-align: right;">-0.126</td>
<td style="text-align: right;">-0.284</td>
<td style="text-align: right;">0.067</td>
<td style="text-align: right;">0.016</td>
<td style="text-align: right;">-0.235</td>
<td style="text-align: right;">0.141</td>
<td style="text-align: right;">0.007</td>
<td style="text-align: right;">-0.002</td>
<td style="text-align: right;">0.082</td>
<td style="text-align: right;">0.083</td>
<td style="text-align: right;">0.133</td>
<td style="text-align: right;">-0.163</td>
<td style="text-align: right;">-0.072</td>
<td style="text-align: right;">0.500</td>
<td style="text-align: right;">0.338</td>
<td style="text-align: right;">-0.390</td>
<td style="text-align: right;">-0.277</td>
<td style="text-align: right;">0.312</td>
<td style="text-align: right;">-0.009</td>
</tr>
<tr class="odd">
<td style="text-align: left;">P_INSEG_OSCURO_2</td>
<td style="text-align: right;">0.207</td>
<td style="text-align: right;">-0.499</td>
<td style="text-align: right;">-0.079</td>
<td style="text-align: right;">0.259</td>
<td style="text-align: right;">-0.165</td>
<td style="text-align: right;">0.099</td>
<td style="text-align: right;">-0.264</td>
<td style="text-align: right;">-0.029</td>
<td style="text-align: right;">0.008</td>
<td style="text-align: right;">-0.081</td>
<td style="text-align: right;">-0.068</td>
<td style="text-align: right;">0.024</td>
<td style="text-align: right;">0.015</td>
<td style="text-align: right;">-0.026</td>
<td style="text-align: right;">-0.245</td>
<td style="text-align: right;">-0.107</td>
<td style="text-align: right;">0.190</td>
<td style="text-align: right;">0.160</td>
<td style="text-align: right;">0.617</td>
<td style="text-align: right;">0.006</td>
</tr>
<tr class="even">
<td style="text-align: left;">P_INSEG_DIA_2</td>
<td style="text-align: right;">0.199</td>
<td style="text-align: right;">-0.541</td>
<td style="text-align: right;">-0.052</td>
<td style="text-align: right;">0.260</td>
<td style="text-align: right;">-0.144</td>
<td style="text-align: right;">0.082</td>
<td style="text-align: right;">-0.222</td>
<td style="text-align: right;">0.007</td>
<td style="text-align: right;">0.004</td>
<td style="text-align: right;">0.034</td>
<td style="text-align: right;">-0.117</td>
<td style="text-align: right;">-0.058</td>
<td style="text-align: right;">0.127</td>
<td style="text-align: right;">0.025</td>
<td style="text-align: right;">0.051</td>
<td style="text-align: right;">0.088</td>
<td style="text-align: right;">-0.125</td>
<td style="text-align: right;">-0.143</td>
<td style="text-align: right;">-0.663</td>
<td style="text-align: right;">0.002</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>En base al análisis realizado, se decide por retener cuatro componentes principales:</p>
<p>PC1: “Percepción General de Inseguridad”</p>
<p>Este componente refleja un patrón amplio de inseguridad, capturando variables como “P_INSEG_LUGARES_1”, “P_INSEG_LUGARES_2”, y “P_INSEG_LUGARES_3”. Estas variables tienen cargas altas y representan situaciones comunes de inseguridad, como caminar por el barrio o estar en espacios públicos. Este componente explica el 32.5% de la varianza total.</p>
<p>PC2: “Inseguridad en Lugares Habituales”</p>
<p>Este componente está dominado por variables como “P_INSEG_OSCURO_2” (inseguridad en casa cuando está oscuro), “P_INSEG_DIA_2” (inseguridad en casa durante el día) y “P_INSEG_LUGARES_14” (inseguridad en lugar de trabajo). Captura sensación de inseguridad en lugares muy familiares para las personas, como su hogar o su lugar de trabajo, explicando un 7.3% de la varianza.</p>
<p>PC3: “Inseguridad en Puntos de espera de Transporte Público”</p>
<p>Este componente agrupa variables como “P_INSEG_LUGARES_8” (terminales de buses o ferrocarriles) y “P_INSEG_LUGARES_2” (espera de transporte público). Refleja la inseguridad asociada a la movilidad y los entornos relacionados, explicando un 5.8% de la varianza.</p>
<p>PC4: “Inseguridad por Traslados”</p>
<p>Componente que refleja sensación de inseguridad a partir de traslados en transporte público, ya sea micros o colectivos. Se encuentra relacionado con componente N° 3.</p>
<section id="mostramos-gráficamente-cómo-las-variables-contribuyen-a-pc1-y-pc2." class="level2">
<h2 class="anchored" data-anchor-id="mostramos-gráficamente-cómo-las-variables-contribuyen-a-pc1-y-pc2.">Mostramos gráficamente cómo las variables contribuyen a PC1 y PC2.</h2>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/variables-inseguridad-pca-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="interpretación-del-gráfico-de-cargas-en-los-primeros-dos-componentes-principales" class="level2">
<h2 class="anchored" data-anchor-id="interpretación-del-gráfico-de-cargas-en-los-primeros-dos-componentes-principales">Interpretación del gráfico de cargas en los primeros dos componentes principales</h2>
<p>PC1: “Percepción General de Inseguridad”</p>
<p>Este componente agrupa variables relacionadas con inseguridad en lugares públicos y situaciones comunes. Variables como P_INSEG_LUGARES_3, P_INSEG_LUGARES_2 y P_INSEG_LUGARES_8 tienen las cargas más altas en este componente. Estas variables representan inseguridad percibida en terminales de transporte, espacios concurridos y al esperar transporte público. Además, P_INSEG_OSCURO_1 (inseguridad al caminar en el barrio durante la noche) es otra variable con alta carga en PC1.</p>
<p>Así, PC1 refleja un patrón amplio de inseguridad en espacios públicos y situaciones que afectan a la mayoría de las personas en su vida cotidiana. Por ello, este componente se puede denominar como “Percepción General de Inseguridad”.</p>
<p>PC2: “Inseguridad en Lugares Habituales”</p>
<p>Este componente captura variables asociadas con espacios privados o habituales, como el hogar y el trabajo. Las variables P_INSEG_DIA_2 (inseguridad al estar solo/a en casa durante el día) y P_INSEG_OSCURO_2 (inseguridad al estar solo/a en casa durante la noche), tienen cargas predominantes en este componente. Además, aparecen variables relacionadas con espacios laborales y educativos, como P_INSEG_LUGARES_14 (inseguridad en el lugar de trabajo) y P_INSEG_LUGARES_15 (inseguridad en el lugar de estudio).</p>
<p>De tal manera, PC2 representa inseguridad en contextos donde las personas suelen sentirse más seguras, como su hogar o trabajo. Este resultado es relevante porque sugiere que, para algunos grupos, la percepción de inseguridad trasciende los espacios públicos y afecta su percepción en lugares privados o controlados. Por ello, PC2 puede denominarse “Inseguridad en Lugares Habituales”.</p>
</section>
</section>
<section id="análisis-de-clusters" class="level1">
<h1>Análisis de clusters</h1>
<p>Una vez ya definimos nuestros cuatro componentes principales, y antes de realizar el análisis de clusters, se procede a realizar modelos predictivos para dos de los cuatro principales encontrados y los dos índices construidos. Con ello, buscamos seguir explorando respecto a las variables, en este caso sociodemográficas, que podrían explicar nuestro fenómeno de interés, la percepción de inseguridad en la sociedad chilena.</p>
<section id="regresión-lineal" class="level2">
<h2 class="anchored" data-anchor-id="regresión-lineal">Regresión Lineal</h2>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Primeras filas del Modelo de Datos Combinados con Componentes Principales</caption>
<colgroup>
<col style="width: 8%">
<col style="width: 9%">
<col style="width: 8%">
<col style="width: 9%">
<col style="width: 3%">
<col style="width: 3%">
<col style="width: 4%">
<col style="width: 3%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 7%">
<col style="width: 4%">
<col style="width: 8%">
<col style="width: 8%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">inseguridad_general</th>
<th style="text-align: right;">inseguridad_habituales</th>
<th style="text-align: right;">inseguridad_espera</th>
<th style="text-align: right;">inseguridad_transporte</th>
<th style="text-align: right;">rph_sexo</th>
<th style="text-align: right;">rph_edad</th>
<th style="text-align: right;">rph_nivel</th>
<th style="text-align: right;">rph_nse</th>
<th style="text-align: right;">rph_situacion_laboral_a</th>
<th style="text-align: right;">rph_pertenencia_indigena</th>
<th style="text-align: right;">rph_nacionalidad</th>
<th style="text-align: right;">rph_idgen</th>
<th style="text-align: right;">indice_inseguridad</th>
<th style="text-align: right;">indice_delincuencia</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">0.2646328</td>
<td style="text-align: right;">0.1403277</td>
<td style="text-align: right;">0.5171485</td>
<td style="text-align: right;">-0.7714967</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">2.500</td>
<td style="text-align: right;">3.000</td>
</tr>
<tr class="even">
<td style="text-align: right;">-2.5041779</td>
<td style="text-align: right;">-0.6406076</td>
<td style="text-align: right;">-0.2661020</td>
<td style="text-align: right;">0.1901180</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2.111</td>
<td style="text-align: right;">2.000</td>
</tr>
<tr class="odd">
<td style="text-align: right;">-1.5800690</td>
<td style="text-align: right;">-0.1983519</td>
<td style="text-align: right;">-1.3465948</td>
<td style="text-align: right;">-1.2255760</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">2.235</td>
<td style="text-align: right;">3.000</td>
</tr>
<tr class="even">
<td style="text-align: right;">-1.5457054</td>
<td style="text-align: right;">-0.1961677</td>
<td style="text-align: right;">-0.1256518</td>
<td style="text-align: right;">0.5333080</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2.000</td>
<td style="text-align: right;">3.000</td>
</tr>
<tr class="odd">
<td style="text-align: right;">-0.7062298</td>
<td style="text-align: right;">-0.0086184</td>
<td style="text-align: right;">0.4411223</td>
<td style="text-align: right;">-0.5814161</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">2.312</td>
<td style="text-align: right;">2.667</td>
</tr>
<tr class="even">
<td style="text-align: right;">-2.4673364</td>
<td style="text-align: right;">-1.2121543</td>
<td style="text-align: right;">0.9966884</td>
<td style="text-align: right;">-0.1808732</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2.067</td>
<td style="text-align: right;">2.333</td>
</tr>
</tbody>
</table>
</div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Distribución de la Variable rph_edad</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Var1</th>
<th style="text-align: right;">Freq</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1</td>
<td style="text-align: right;">18554</td>
</tr>
<tr class="even">
<td style="text-align: left;">2</td>
<td style="text-align: right;">22949</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3</td>
<td style="text-align: right;">6961</td>
</tr>
</tbody>
</table>
</div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Proporción de la Variable rph_edad (%)</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Var1</th>
<th style="text-align: right;">Freq</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1</td>
<td style="text-align: right;">38.28409</td>
</tr>
<tr class="even">
<td style="text-align: left;">2</td>
<td style="text-align: right;">47.35267</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3</td>
<td style="text-align: right;">14.36324</td>
</tr>
</tbody>
</table>
</div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Numero de casos por nivel educacional</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Var1</th>
<th style="text-align: right;">Freq</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">0</td>
<td style="text-align: right;">359</td>
</tr>
<tr class="even">
<td style="text-align: left;">1</td>
<td style="text-align: right;">8309</td>
</tr>
<tr class="odd">
<td style="text-align: left;">2</td>
<td style="text-align: right;">22276</td>
</tr>
<tr class="even">
<td style="text-align: left;">3</td>
<td style="text-align: right;">17520</td>
</tr>
</tbody>
</table>
</div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Nueva estructura de nivel educacional</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Var1</th>
<th style="text-align: right;">Freq</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1</td>
<td style="text-align: right;">8309</td>
</tr>
<tr class="even">
<td style="text-align: left;">2</td>
<td style="text-align: right;">22276</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3</td>
<td style="text-align: right;">17520</td>
</tr>
</tbody>
</table>
</div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Resumen del Modelo CP1</caption>
<colgroup>
<col style="width: 32%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 15%">
<col style="width: 24%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">Estimate</th>
<th style="text-align: right;">Std. Error</th>
<th style="text-align: right;">t value</th>
<th style="text-align: right;">Pr(&gt;|t|)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">-1.3581765</td>
<td style="text-align: right;">0.0539689</td>
<td style="text-align: right;">-25.1659110</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="even">
<td style="text-align: left;">rph_sexo2</td>
<td style="text-align: right;">1.2227724</td>
<td style="text-align: right;">0.8197660</td>
<td style="text-align: right;">1.4916114</td>
<td style="text-align: right;">0.1358076</td>
</tr>
<tr class="odd">
<td style="text-align: left;">rph_edad</td>
<td style="text-align: right;">0.2925336</td>
<td style="text-align: right;">0.0184658</td>
<td style="text-align: right;">15.8419428</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="even">
<td style="text-align: left;">rph_nivel2</td>
<td style="text-align: right;">0.3255787</td>
<td style="text-align: right;">0.0344730</td>
<td style="text-align: right;">9.4444574</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">rph_nivel3</td>
<td style="text-align: right;">0.2784147</td>
<td style="text-align: right;">0.0408237</td>
<td style="text-align: right;">6.8199242</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="even">
<td style="text-align: left;">rph_nse2</td>
<td style="text-align: right;">-0.1471550</td>
<td style="text-align: right;">0.0269048</td>
<td style="text-align: right;">-5.4694614</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">rph_nse3</td>
<td style="text-align: right;">-0.8275294</td>
<td style="text-align: right;">0.0413080</td>
<td style="text-align: right;">-20.0331672</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="even">
<td style="text-align: left;">rph_situacion_laboral_a1</td>
<td style="text-align: right;">0.4611392</td>
<td style="text-align: right;">0.0247969</td>
<td style="text-align: right;">18.5966133</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">rph_pertenencia_indigena1</td>
<td style="text-align: right;">-0.0777177</td>
<td style="text-align: right;">0.0399418</td>
<td style="text-align: right;">-1.9457748</td>
<td style="text-align: right;">0.0516876</td>
</tr>
<tr class="even">
<td style="text-align: left;">rph_nacionalidad2</td>
<td style="text-align: right;">-0.2761773</td>
<td style="text-align: right;">0.0480463</td>
<td style="text-align: right;">-5.7481546</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">rph_idgen2</td>
<td style="text-align: right;">-0.2727773</td>
<td style="text-align: right;">0.8199436</td>
<td style="text-align: right;">-0.3326782</td>
<td style="text-align: right;">0.7393787</td>
</tr>
<tr class="even">
<td style="text-align: left;">rph_idgen3</td>
<td style="text-align: right;">0.0664214</td>
<td style="text-align: right;">0.7269648</td>
<td style="text-align: right;">0.0913682</td>
<td style="text-align: right;">0.9272004</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Resumen del modelo:</p>
<p>rph_edad: La edad tiene un efecto positivo significativo sobre la inseguridad general. Cada unidad de aumento en la edad se asocia con un incremento de 0,29 unidades en el componente inseguridad_general.</p>
<p>rph_nivel: Los niveles educativos más altos (rph_nivel2 y rph_nivel3) están asociados con mayor percepción de inseguridad en comparación con el nivel de referencia (nivel 1: “Educación Básica”). Esto podría reflejar que mayores niveles educativos están relacionados con mayor consciencia sobre los riesgos.</p>
<p>rph_nse: Los niveles socioeconómicos más altos (rph_nse2 y rph_nse3) están asociados con una percepción menor de inseguridad, en línea con la hipótesis de que los entornos de mayor NSE suelen ser más seguros o percibidos como tal.</p>
<p>rph_situacion_laboral_a: Las personas empleadas (1) perciben una mayor inseguridad general (coeficiente positivo de 0,46). Esto podría estar relacionado con su exposición a situaciones de inseguridad al trasladarse o trabajar fuera del hogar.</p>
<p>rph_nacionalidad2: Las personas con doble nacionalidad o extranjeras tienden a percibir menos inseguridad general (coeficiente negativo de 0,28 unidades).</p>
<p>El resto de las variables no son significativas para precedir variabilidad de componente “inseguridad_general”</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Resumen del Modelo CP2</caption>
<colgroup>
<col style="width: 33%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 24%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">Estimate</th>
<th style="text-align: right;">Std. Error</th>
<th style="text-align: right;">t value</th>
<th style="text-align: right;">Pr(&gt;|t|)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">-0.0258430</td>
<td style="text-align: right;">0.0257008</td>
<td style="text-align: right;">-1.005532</td>
<td style="text-align: right;">0.3146459</td>
</tr>
<tr class="even">
<td style="text-align: left;">rph_sexo2</td>
<td style="text-align: right;">0.7309303</td>
<td style="text-align: right;">0.3903854</td>
<td style="text-align: right;">1.872330</td>
<td style="text-align: right;">0.0611671</td>
</tr>
<tr class="odd">
<td style="text-align: left;">rph_edad</td>
<td style="text-align: right;">-0.1071209</td>
<td style="text-align: right;">0.0087937</td>
<td style="text-align: right;">-12.181574</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="even">
<td style="text-align: left;">rph_nivel2</td>
<td style="text-align: right;">0.0503310</td>
<td style="text-align: right;">0.0164166</td>
<td style="text-align: right;">3.065862</td>
<td style="text-align: right;">0.0021716</td>
</tr>
<tr class="odd">
<td style="text-align: left;">rph_nivel3</td>
<td style="text-align: right;">0.2341603</td>
<td style="text-align: right;">0.0194409</td>
<td style="text-align: right;">12.044732</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="even">
<td style="text-align: left;">rph_nse2</td>
<td style="text-align: right;">0.1399422</td>
<td style="text-align: right;">0.0128125</td>
<td style="text-align: right;">10.922315</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">rph_nse3</td>
<td style="text-align: right;">0.4124217</td>
<td style="text-align: right;">0.0196715</td>
<td style="text-align: right;">20.965443</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="even">
<td style="text-align: left;">rph_situacion_laboral_a1</td>
<td style="text-align: right;">0.0322604</td>
<td style="text-align: right;">0.0118087</td>
<td style="text-align: right;">2.731919</td>
<td style="text-align: right;">0.0062990</td>
</tr>
<tr class="odd">
<td style="text-align: left;">rph_pertenencia_indigena1</td>
<td style="text-align: right;">-0.0923511</td>
<td style="text-align: right;">0.0190209</td>
<td style="text-align: right;">-4.855244</td>
<td style="text-align: right;">0.0000012</td>
</tr>
<tr class="even">
<td style="text-align: left;">rph_nacionalidad2</td>
<td style="text-align: right;">-0.0933082</td>
<td style="text-align: right;">0.0228804</td>
<td style="text-align: right;">-4.078086</td>
<td style="text-align: right;">0.0000455</td>
</tr>
<tr class="odd">
<td style="text-align: left;">rph_idgen2</td>
<td style="text-align: right;">-0.7452374</td>
<td style="text-align: right;">0.3904699</td>
<td style="text-align: right;">-1.908565</td>
<td style="text-align: right;">0.0563242</td>
</tr>
<tr class="even">
<td style="text-align: left;">rph_idgen3</td>
<td style="text-align: right;">0.3693150</td>
<td style="text-align: right;">0.3461920</td>
<td style="text-align: right;">1.066793</td>
<td style="text-align: right;">0.2860709</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Resumen del modelo:</p>
<p>rph_edad: Relación negativa significativa (-0,10). A mayor edad, menor es la percepción de inseguridad en lugares habituales. Esto puede reflejar que personas mayores se sienten más seguras en sus espacios privados.</p>
<p>rph_nivel3: Personas con educación superior tienen una percepción significativamente mayor de inseguridad en lugares habituales en comparación con quienes tienen estudios básicos (coeficiente 0,23).</p>
<p>rph_nse: A medida que el nivel socioeconómico aumenta (rph_nse2 y rph_nse3), la percepción de inseguridad habitual también aumenta.</p>
<p>rph_situacion_laboral_a1: Las personas empleadas tienen una percepción ligeramente mayor de inseguridad en lugares habituales (coeficiente 0,032).</p>
<p>rph_pertenencia_indigena1: Pertenecer a un pueblo indígena se asocia con una menor percepción de inseguridad habitual (-0,092). Esto podría estar relacionado con diferencias culturales o contextos específicos donde habitan estas personas.</p>
<p>rph_nacionalidad2: Las personas extranjeras o con doble nacionalidad perciben menos inseguridad habitual (-0,097).</p>
<p>Como podemos observar, las relaciones entre nuestras variables independientes respecto al CP 2 se desvían respecto a las relaciones existentes en el primer modelo de regresión. Las personas en espacios privados tienen diferentes razones para sentirse inseguras. Llama la atención que los adultos mayores y las personas pertenecientes a pueblos indígenas se sientan significativamente más seguras en sus espacios de desarrollo habitual que el resto de la población chilena.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Resumen del Modelo de Inseguridad</caption>
<colgroup>
<col style="width: 32%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 15%">
<col style="width: 24%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">Estimate</th>
<th style="text-align: right;">Std. Error</th>
<th style="text-align: right;">t value</th>
<th style="text-align: right;">Pr(&gt;|t|)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">2.2343543</td>
<td style="text-align: right;">0.0085834</td>
<td style="text-align: right;">260.3111492</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="even">
<td style="text-align: left;">rph_sexo2</td>
<td style="text-align: right;">0.1693952</td>
<td style="text-align: right;">0.1303784</td>
<td style="text-align: right;">1.2992582</td>
<td style="text-align: right;">0.1938616</td>
</tr>
<tr class="odd">
<td style="text-align: left;">rph_edad</td>
<td style="text-align: right;">0.0319150</td>
<td style="text-align: right;">0.0029369</td>
<td style="text-align: right;">10.8670427</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="even">
<td style="text-align: left;">rph_nivel2</td>
<td style="text-align: right;">0.0566381</td>
<td style="text-align: right;">0.0054827</td>
<td style="text-align: right;">10.3303265</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">rph_nivel3</td>
<td style="text-align: right;">0.0470020</td>
<td style="text-align: right;">0.0064927</td>
<td style="text-align: right;">7.2391577</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="even">
<td style="text-align: left;">rph_nse2</td>
<td style="text-align: right;">-0.0284088</td>
<td style="text-align: right;">0.0042790</td>
<td style="text-align: right;">-6.6390627</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">rph_nse3</td>
<td style="text-align: right;">-0.1351299</td>
<td style="text-align: right;">0.0065698</td>
<td style="text-align: right;">-20.5684630</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="even">
<td style="text-align: left;">rph_situacion_laboral_a1</td>
<td style="text-align: right;">0.0613436</td>
<td style="text-align: right;">0.0039438</td>
<td style="text-align: right;">15.5544613</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">rph_pertenencia_indigena1</td>
<td style="text-align: right;">-0.0130381</td>
<td style="text-align: right;">0.0063525</td>
<td style="text-align: right;">-2.0524426</td>
<td style="text-align: right;">0.0401321</td>
</tr>
<tr class="even">
<td style="text-align: left;">rph_nacionalidad2</td>
<td style="text-align: right;">-0.0484301</td>
<td style="text-align: right;">0.0076414</td>
<td style="text-align: right;">-6.3378204</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">rph_idgen2</td>
<td style="text-align: right;">-0.0184841</td>
<td style="text-align: right;">0.1304066</td>
<td style="text-align: right;">-0.1417416</td>
<td style="text-align: right;">0.8872847</td>
</tr>
<tr class="even">
<td style="text-align: left;">rph_idgen3</td>
<td style="text-align: right;">0.0359817</td>
<td style="text-align: right;">0.1156190</td>
<td style="text-align: right;">0.3112095</td>
<td style="text-align: right;">0.7556427</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Resumen del modelo:</p>
<p>rph_edad: A medida que aumenta la edad, también lo hace el índice de inseguridad, lo que indica que las personas mayores perciben más inseguridad en términos generales.</p>
<p>rph_nivel (niveles 1, 2, 3): Las personas con más años de educación tienen una percepción ligeramente mayor de inseguridad.</p>
<p>rph_nse (niveles 2, 3): A medida que aumenta el nivel socioeconómico, el índice de inseguridad tiende a disminuir. Esto podría reflejar entornos más protegidos o mayor acceso a recursos de seguridad.</p>
<p>rph_situacion_laboral_a1: Las personas laboralmente activas tienen una percepción ligeramente mayor de inseguridad en comparación con quienes no están empleados.</p>
<p>rph_nacionalidad2: Las personas extranjeras o con doble nacionalidad tienen un índice de inseguridad ligeramente menor en comparación con los chilenos.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Resumen del Modelo de Delincuencia</caption>
<colgroup>
<col style="width: 32%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 15%">
<col style="width: 24%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">Estimate</th>
<th style="text-align: right;">Std. Error</th>
<th style="text-align: right;">t value</th>
<th style="text-align: right;">Pr(&gt;|t|)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">2.5570176</td>
<td style="text-align: right;">0.0082335</td>
<td style="text-align: right;">310.5640866</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="even">
<td style="text-align: left;">rph_sexo2</td>
<td style="text-align: right;">0.0221434</td>
<td style="text-align: right;">0.1250630</td>
<td style="text-align: right;">0.1770576</td>
<td style="text-align: right;">0.8594639</td>
</tr>
<tr class="odd">
<td style="text-align: left;">rph_edad</td>
<td style="text-align: right;">0.0347207</td>
<td style="text-align: right;">0.0028171</td>
<td style="text-align: right;">12.3248694</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="even">
<td style="text-align: left;">rph_nivel2</td>
<td style="text-align: right;">0.0308526</td>
<td style="text-align: right;">0.0052592</td>
<td style="text-align: right;">5.8664199</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">rph_nivel3</td>
<td style="text-align: right;">0.0302877</td>
<td style="text-align: right;">0.0062280</td>
<td style="text-align: right;">4.8631113</td>
<td style="text-align: right;">0.0000012</td>
</tr>
<tr class="even">
<td style="text-align: left;">rph_nse2</td>
<td style="text-align: right;">-0.0135761</td>
<td style="text-align: right;">0.0041046</td>
<td style="text-align: right;">-3.3075384</td>
<td style="text-align: right;">0.0009419</td>
</tr>
<tr class="odd">
<td style="text-align: left;">rph_nse3</td>
<td style="text-align: right;">-0.0890197</td>
<td style="text-align: right;">0.0063019</td>
<td style="text-align: right;">-14.1258049</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="even">
<td style="text-align: left;">rph_situacion_laboral_a1</td>
<td style="text-align: right;">0.0659978</td>
<td style="text-align: right;">0.0037830</td>
<td style="text-align: right;">17.4458488</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">rph_pertenencia_indigena1</td>
<td style="text-align: right;">-0.0017946</td>
<td style="text-align: right;">0.0060935</td>
<td style="text-align: right;">-0.2945155</td>
<td style="text-align: right;">0.7683653</td>
</tr>
<tr class="even">
<td style="text-align: left;">rph_nacionalidad2</td>
<td style="text-align: right;">-0.0785402</td>
<td style="text-align: right;">0.0073299</td>
<td style="text-align: right;">-10.7150282</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">rph_idgen2</td>
<td style="text-align: right;">0.0536546</td>
<td style="text-align: right;">0.1250901</td>
<td style="text-align: right;">0.4289276</td>
<td style="text-align: right;">0.6679779</td>
</tr>
<tr class="even">
<td style="text-align: left;">rph_idgen3</td>
<td style="text-align: right;">-0.3034142</td>
<td style="text-align: right;">0.1109053</td>
<td style="text-align: right;">-2.7357949</td>
<td style="text-align: right;">0.0062253</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Resumen del modelo:</p>
<p>rph_edad: A medida que aumenta la edad, también lo hace el índice de percepción de delincuencia, lo que indica que las personas mayores perciben mayores niveles de delincuencia.</p>
<p>rph_nivel (niveles 2, 3): Las personas con más años de educación perciben niveles ligeramente mayores de delincuencia.</p>
<p>rph_nse (niveles 2, 3): A medida que aumenta el nivel socioeconómico, el índice de percepción de delincuencia disminuye, posiblemente reflejando mayor protección en estos entornos.</p>
<p>rph_situacion_laboral_a1: Las personas laboralmente activas tienen una percepción ligeramente mayor de delincuencia en comparación con quienes no están empleados.</p>
<p>rph_nacionalidad2: Las personas extranjeras o con doble nacionalidad perciben niveles ligeramente menores de delincuencia en comparación con los chilenos.</p>
<p>A modo de síntesis, en general, los modelos predictivos muestran que las variables sociodemográficas tienen un impacto relevante, aunque moderado, en la percepción de inseguridad y delincuencia. La edad emerge como un factor consistente que incrementa ambas percepciones, lo que podría estar vinculado a una mayor vulnerabilidad percibida en las personas mayores.</p>
<p>Las personas con más educación tienden a percibir mayores niveles de inseguridad y delincuencia, probablemente debido a una mayor exposición a información sobre riesgos o una mayor conciencia de los mismos. Por otro lado, el nivel socioeconómico (NSE) muestra una relación inversa: a medida que este aumenta, las percepciones de inseguridad y delincuencia disminuyen, reflejando probablemente entornos más protegidos o con mayor acceso a recursos de seguridad.</p>
<p>Estar laboralmente activo también se asocia con percepciones ligeramente más altas de inseguridad y delincuencia, lo que podría estar relacionado con una mayor movilidad y exposición en espacios públicos.</p>
<p>Finalmente, las personas con nacionalidad extranjera o doble nacionalidad tienden a percibir menores niveles de inseguridad y delincuencia, lo que podría reflejar diferencias culturales o expectativas distintas en cuanto a la seguridad.</p>
<p>Más allá de lo anterior, es relevante mencionar que la capacidad explicativa de nuestros modelos es bastante baja, variando entre un R² de 2% y 5% y con una cantidad considerable de residuos. Por lo anterior, debemos establecer que parte importante de la variabilidad de nuestros factores a explicar no es capturada por nuestros modelos. Así, más allá de las variables sociodemográficas, existirían otro tipo de variables independientes a partir de las cuales se podría predecir, de manera más completa, nuestro fenómeno de interés.</p>
<p>Creando los clusters</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Resumen Estadístico de Clústeres</caption>
<colgroup>
<col style="width: 4%">
<col style="width: 5%">
<col style="width: 16%">
<col style="width: 14%">
<col style="width: 11%">
<col style="width: 9%">
<col style="width: 8%">
<col style="width: 7%">
<col style="width: 11%">
<col style="width: 9%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">Cluster</th>
<th style="text-align: right;">Cantidad</th>
<th style="text-align: right;">Media (Inseguridad General)</th>
<th style="text-align: right;">SD (Inseguridad General)</th>
<th style="text-align: right;">Media (Habituales)</th>
<th style="text-align: right;">SD (Habituales)</th>
<th style="text-align: right;">Media (Espera)</th>
<th style="text-align: right;">SD (Espera)</th>
<th style="text-align: right;">Media (Transporte)</th>
<th style="text-align: right;">SD (Transporte)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: right;">27476</td>
<td style="text-align: right;">-1.452006</td>
<td style="text-align: right;">1.779916</td>
<td style="text-align: right;">-0.1914942</td>
<td style="text-align: right;">1.057818</td>
<td style="text-align: right;">0.3892163</td>
<td style="text-align: right;">0.8604005</td>
<td style="text-align: right;">0.0111135</td>
<td style="text-align: right;">0.9506389</td>
</tr>
<tr class="even">
<td style="text-align: right;">2</td>
<td style="text-align: right;">20629</td>
<td style="text-align: right;">1.937097</td>
<td style="text-align: right;">2.106771</td>
<td style="text-align: right;">0.2614730</td>
<td style="text-align: right;">1.340722</td>
<td style="text-align: right;">-0.5196089</td>
<td style="text-align: right;">1.1296959</td>
<td style="text-align: right;">-0.0150965</td>
<td style="text-align: right;">1.1109082</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Cluster 1: Según los datos, vemos que el cluster 1 tiene una media de inseguridad general negativa, de un -1,45. Respecto a la inseguridad habitual, también esta es negativa, con un valor de -0,191. Respecto a la espera observamos que tienen una inseguridad positiva respecto a la espera (0,387) y una tasa también positiva de inseguridad respecto a la movilización en transporte público (0,014). El cluster tiene un total de 28.020 observaciones.</p>
<p>Cluster 2: En este cluster vemos una inseguridad general positiva, de 1,95. Del mismo modo, observamos que su media de inseguridad en lugares habituales de desarrollo personal es de 0,26. No obstante, en la espera de transporte público tienen una media de inseguridad negativa de -0,52 y una inseguridad en medios de transporte público también negativa, de un -0,018. El cluster tiene un total de 21.019 observaciones.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/clustering-visualización-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Como podemos observar, la diferencia entre ambos cluster ronda en torno a la inseguridad general. Mientras que el cluster 1 presenta menores niveles de inseguridad general, el cluster 2 representa a personas con mayores niveles de inseguridad. De tal manera, este sería el componente principal clave (la percepción general de inseguridad), a partir del cual es posible diferenciar a ambos grupos.</p>
<p>Se incorporan etiquetas a los clusters, en beneficio de la visualización de nuestros datos:</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Distribución de los clusters</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Var1</th>
<th style="text-align: right;">Freq</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Cluster 1: Baja inseguridad general</td>
<td style="text-align: right;">27476</td>
</tr>
<tr class="even">
<td style="text-align: left;">Cluster 2: Alta inseguridad general</td>
<td style="text-align: right;">20629</td>
</tr>
</tbody>
</table>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/clustering-2-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Presentamos un gráfico de densidad de nuestros clusters</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/cluster-grafico-densidad-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Caracterizando a nuestros conglomerados</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Caracterización de los Clústeres</caption>
<colgroup>
<col style="width: 11%">
<col style="width: 7%">
<col style="width: 4%">
<col style="width: 3%">
<col style="width: 3%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 7%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 5%">
<col style="width: 4%">
<col style="width: 4%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Cluster</th>
<th style="text-align: right;">Número de Observaciones</th>
<th style="text-align: right;">Edad Promedio</th>
<th style="text-align: right;">Hombres (%)</th>
<th style="text-align: right;">Mujeres (%)</th>
<th style="text-align: right;">Educación Básica (%)</th>
<th style="text-align: right;">Educación Media (%)</th>
<th style="text-align: right;">Educación Superior (%)</th>
<th style="text-align: right;">NSE Bajo (%)</th>
<th style="text-align: right;">NSE Medio (%)</th>
<th style="text-align: right;">NSE Alto (%)</th>
<th style="text-align: right;">Activos Laboralmente (%)</th>
<th style="text-align: right;">Inactivos Laboralmente</th>
<th style="text-align: right;">Pertenencia Indígena (%)</th>
<th style="text-align: right;">No Indígenas (%)</th>
<th style="text-align: right;">Chilenos (%)</th>
<th style="text-align: right;">Extranjeros (%)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Cluster 1: Baja inseguridad general</td>
<td style="text-align: right;">27476</td>
<td style="text-align: right;">1.759899</td>
<td style="text-align: right;">48.17659</td>
<td style="text-align: right;">51.82341</td>
<td style="text-align: right;">19.13306</td>
<td style="text-align: right;">46.13117</td>
<td style="text-align: right;">34.73577</td>
<td style="text-align: right;">47.85267</td>
<td style="text-align: right;">38.39715</td>
<td style="text-align: right;">13.75018</td>
<td style="text-align: right;">53.23919</td>
<td style="text-align: right;">46.76081</td>
<td style="text-align: right;">9.375455</td>
<td style="text-align: right;">90.62455</td>
<td style="text-align: right;">94.23861</td>
<td style="text-align: right;">5.761392</td>
</tr>
<tr class="even">
<td style="text-align: left;">Cluster 2: Alta inseguridad general</td>
<td style="text-align: right;">20629</td>
<td style="text-align: right;">1.745989</td>
<td style="text-align: right;">38.63493</td>
<td style="text-align: right;">61.36507</td>
<td style="text-align: right;">14.79471</td>
<td style="text-align: right;">46.54128</td>
<td style="text-align: right;">38.66402</td>
<td style="text-align: right;">45.69296</td>
<td style="text-align: right;">40.47700</td>
<td style="text-align: right;">13.83005</td>
<td style="text-align: right;">59.53754</td>
<td style="text-align: right;">40.46246</td>
<td style="text-align: right;">8.672258</td>
<td style="text-align: right;">91.32774</td>
<td style="text-align: right;">93.41703</td>
<td style="text-align: right;">6.582966</td>
</tr>
</tbody>
</table>
</div>
</div>
<section id="cruce-de-clusters-con-variables-sociodemográficas-seleccionadas" class="level3">
<h3 class="anchored" data-anchor-id="cruce-de-clusters-con-variables-sociodemográficas-seleccionadas">Cruce de clusters con variables sociodemográficas seleccionadas</h3>
<p>En base a los resultados arrojados por los modelos de regresión lineal múltiple, por caracterizar los clusters en base a nuestras variables más significativas: 1) Nivel socioeconómico, 2) Edad, 3) Sexo, 4) Condición laboral</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Resumen de Inseguridad por Cluster y NSE</caption>
<colgroup>
<col style="width: 35%">
<col style="width: 3%">
<col style="width: 28%">
<col style="width: 31%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Cluster</th>
<th style="text-align: left;">NSE</th>
<th style="text-align: right;">Promedio Inseguridad General</th>
<th style="text-align: right;">Promedio Inseguridad Habituales</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Cluster 1: Baja inseguridad general</td>
<td style="text-align: left;">1</td>
<td style="text-align: right;">-1.227719</td>
<td style="text-align: right;">-0.3339878</td>
</tr>
<tr class="even">
<td style="text-align: left;">Cluster 1: Baja inseguridad general</td>
<td style="text-align: left;">2</td>
<td style="text-align: right;">-1.483505</td>
<td style="text-align: right;">-0.1616005</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Cluster 1: Baja inseguridad general</td>
<td style="text-align: left;">3</td>
<td style="text-align: right;">-2.144598</td>
<td style="text-align: right;">0.2209271</td>
</tr>
<tr class="even">
<td style="text-align: left;">Cluster 2: Alta inseguridad general</td>
<td style="text-align: left;">1</td>
<td style="text-align: right;">2.027701</td>
<td style="text-align: right;">0.0704709</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Cluster 2: Alta inseguridad general</td>
<td style="text-align: left;">2</td>
<td style="text-align: right;">2.010877</td>
<td style="text-align: right;">0.3178629</td>
</tr>
<tr class="even">
<td style="text-align: left;">Cluster 2: Alta inseguridad general</td>
<td style="text-align: left;">3</td>
<td style="text-align: right;">1.421814</td>
<td style="text-align: right;">0.7274843</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/cluster-nse-grafico-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Como podemos observar, el nivel socioeconómico posee una relación relativamente lineal respecto al nivel de inseguridad. A mayor NSE, menores niveles de inseguridad.</p>
<p>Como vemos en el cluster 1, el NSE bajo es el que posee un menor nivel de seguridad, el NSE medio registra mayores niveles de seguridad y el NSE 3 (o “alto”), posee la más alta tasa de seguridad. Análogamente, al analizar el cluster dos, vemos que el grupo con mayores niveles de inseguridad es el grupo socioeconómico bajo (1), seguido por la categoría que representa al NSE medio, mientras que el grupo socioeconómico con menores niveles de inseguridad es el representado por la categoría 3, o Nivel Socioeconómico alto.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Resumen de Inseguridad por Cluster y Edad</caption>
<colgroup>
<col style="width: 31%">
<col style="width: 15%">
<col style="width: 25%">
<col style="width: 27%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Cluster</th>
<th style="text-align: right;">Edad (Categorías)</th>
<th style="text-align: right;">Promedio Inseguridad General</th>
<th style="text-align: right;">Promedio Inseguridad Habituales</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Cluster 1: Baja inseguridad general</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">-1.749354</td>
<td style="text-align: right;">-0.1084632</td>
</tr>
<tr class="even">
<td style="text-align: left;">Cluster 1: Baja inseguridad general</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">-1.282516</td>
<td style="text-align: right;">-0.2281448</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Cluster 1: Baja inseguridad general</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">-1.169703</td>
<td style="text-align: right;">-0.2990108</td>
</tr>
<tr class="even">
<td style="text-align: left;">Cluster 2: Alta inseguridad general</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1.681888</td>
<td style="text-align: right;">0.4599894</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Cluster 2: Alta inseguridad general</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">2.154283</td>
<td style="text-align: right;">0.1855507</td>
</tr>
<tr class="even">
<td style="text-align: left;">Cluster 2: Alta inseguridad general</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">1.734382</td>
<td style="text-align: right;">-0.0318598</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/cluster-edad-grafico-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Como podemos observar, las personas más jóvenes (categoría 1) tienen los niveles de inseguridad más bajos dentro del cluster 1 (Baja Inseguridad General), con un promedio de -1,74.Conforme aumenta la edad (categorías 2 y 3), se incrementa ligeramente la percepción de inseguridad, alcanzando un promedio de -1.16 en la categoría 3.</p>
<p>Respecto al Cluster 2 (Alta inseguridad general), las personas de edad intermedia (categoría 2) presentan los niveles más altos de inseguridad general, con un promedio de 2.16. Las personas más jóvenes (categoría 1) y las más mayores (categoría 3) tienen niveles ligeramente más bajos de inseguridad dentro de este cluster, con promedios de 1.68 y 1.74, respectivamente.</p>
<p>Estos resultados sugieren que la percepción de inseguridad puede estar influenciada por la edad, con patrones distintos dependiendo del grupo al que pertenecen las personas.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Proporción de Observaciones por Sexo y Cluster</caption>
<colgroup>
<col style="width: 40%">
<col style="width: 32%">
<col style="width: 10%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Cluster</th>
<th style="text-align: left;">Sexo (1 = Hombre, 2 = Mujer)</th>
<th style="text-align: right;">Cantidad</th>
<th style="text-align: right;">Proporción (%)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Cluster 1: Baja inseguridad general</td>
<td style="text-align: left;">1</td>
<td style="text-align: right;">13237</td>
<td style="text-align: right;">48.17659</td>
</tr>
<tr class="even">
<td style="text-align: left;">Cluster 1: Baja inseguridad general</td>
<td style="text-align: left;">2</td>
<td style="text-align: right;">14239</td>
<td style="text-align: right;">51.82341</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Cluster 2: Alta inseguridad general</td>
<td style="text-align: left;">1</td>
<td style="text-align: right;">7970</td>
<td style="text-align: right;">38.63493</td>
</tr>
<tr class="even">
<td style="text-align: left;">Cluster 2: Alta inseguridad general</td>
<td style="text-align: left;">2</td>
<td style="text-align: right;">12659</td>
<td style="text-align: right;">61.36507</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/cluster-sexo-grafico-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>El gráfico evidencia claramente que las mujeres, en promedio, tienen menores niveles de seguridad y mayores niveles de inseguridad en comparación con los hombres en ambos clusters. La distribución y proporción de sexo en los clusters confirma la hipótesis de que las mujeres experimentan mayores niveles de inseguridad en comparación con los hombres. Esto se refleja de manera consistente tanto en las proporciones de observaciones como en los promedios de inseguridad general por sexo.</p>
<p>#Graficamos la composición de nuestros clusters según la situación laboral de las personas entrevistadas</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/cluster-actividad-laboral-grafico-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Finalmente, respecto a la variación de percepción de inseguridad según su actividad laboral, podemos establecer que Las personas activas laboralmente perciben y manifiestan mayores niveles de inseguridad en comparación con las inactivas. Esto se evidencia porque una proporción significativa de personas activas laboralmente está presente en el Cluster 2, que representa alta inseguridad.</p>
<p>En contraste, las personas inactivas laboralmente tienden a percibir menor inseguridad, lo que explica su mayor presencia proporcional en el Cluster 1 (Baja Inseguridad General).</p>
<p>De tal manera, las personas activas laboralmente pueden estar más expuestas a factores que aumentan su percepción de inseguridad, como desplazamientos diarios, interacción en entornos públicos y horarios variados, lo que incrementa la probabilidad de enfrentar situaciones riesgosas.Por su parte, las personas inactivas laboralmente, al pasar más tiempo en entornos privados o controlados, podrían estar menos expuestas a situaciones de inseguridad, lo que reduce su percepción del riesgo.</p>
</section>
</section>
</section>
<section id="conclusiones" class="level1">
<h1>Conclusiones</h1>
<p>A partir de los resultados obtenidos en el presente trabajo, podemos establecer que no es posible segmentar a la población chilena de forma clara según su percepción de inseguridad declarada. Si bien el análisis de clusters permitió identificar dos grandes conglomerados (uno con mayores niveles de inseguridad y otro con menores niveles), estos grupos se traslapan entre sí, lo que evidencia un bajo nivel de diferenciación entre ellos.</p>
<p>Más allá de lo anterior, y respecto a los dos conglomerados a partir de los que se determinó continuar con la investigación, podemos indicar que el cluster 1, que representa un nivel menor de inseguridad que el promedio, se asocia con grupos conformados por hombres, con individuos que pertenecen al nivel socioeconómico alto, con grupos etarios jóvenes y sin actividad laboral, entre otras características diferenciadoras a nivel sociodemográfico.</p>
<p>En contraste, el cluster 2, que representa niveles de percepción de inseguridad más altos que el promedio de nuestra sociedad, se relaciona mayormente con mujeres, con individuos pertenencientes a los niveles socioeconómicos bajos y medios, con personas que se encuentran trabajando y con grupos etarios medios y avanzados de la población.</p>
<p>Este hallazgo, consistente con la literatura sobre el fenómeno, refuerza la idea de que la inseguridad es un fenómeno transversal, aunque no homogéneo, en la sociedad chilena. Es decir, afecta a toda la población, aunque ciertos grupos experimentan niveles ligeramente mayores o menores. Las diferencias intra-grupales identificadas, aunque estadísticamente significativas (por ejemplo, según edad, sexo, nacionalidad, NSE, etc.), no son lo suficientemente marcadas como para definir perfiles claramente distinguibles dentro de la sociedad.</p>
<p>De esta manera, la percepción de inseguridad puede considerarse como una preocupación social que impacta de manera generalizada la calidad de vida en el país, alcanzando niveles medio-altos en promedio. Este resultado sugiere que las políticas públicas deben abordar el problema desde una perspectiva amplia y universal, pero con enfoques diferenciados y planes de acción específicos, para atender las necesidades y requerimientos de los grupos más afectados, como lo son las mujeres, las personas mayores, los individuos de menor nivel socioeconómico, los trabajadores activos, entre otros segmentos de la población, que sufren mayormente las consecuencias, ya sean materiales o inmateriales, del fenómeno delictivo y de otros fenómenos relacionados que afectan el bienestar de nuestra sociedad.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copiado");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copiado");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>